import React, { createContext, useContext, useEffect, useState } from 'react';

type Language = 'ar' | 'en';
type Direction = 'rtl' | 'ltr';

interface LanguageContextType {
  language: Language;
  direction: Direction;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  ar: {
    'dashboard': 'الرئيسية',
    'products': 'الأصناف',
    'products_list': 'قائمة الأصناف',
    'add_product': 'اضافة الصنف',
    'import_products': 'استيراد الأصناف',
    'print_barcode': 'طباعة باركود - الملصقات',
    'quantity_adjustments': 'التعديلات الكمية',

    'groups': 'التصنيفات',
    'add_new_group': 'إضافة تصنيفة جديده',
    'units': 'الوحدات',
    'group_code': 'كود التصنيف',
    'group_name': 'اسم التصنيف',
    'group_name_secondary_lang': 'اسم التصنيف باللغة الثانية',
    'group_image': 'صورة التصنيف',
    'add_new_unit': 'اضافة وحدة جديده',
    'unit_code': 'كود الوحده',
    'unit_name': 'اسم الوحده',
    'sales': 'المبيعات',
    'all_sales': 'جميع المبيعات',
    'sales_a4_quick': 'مبيعات A4',
    'a4_sales_title': 'إضافة مبيعات A4',
    'add_sale_operation': 'اضافة عمليه بيع',
    'cashier': 'كاشير',
    'branch': 'الفرع',
    'customer_label': 'عميل',
    'delegate_employee': 'المندوب / الموظف',
    'po_number': 'رقم أمر الشراء',
    'project_name': 'اسم المشروع',
    'please_add_items': 'الرجاء إضافة الأصناف',
    'update_options_before_adding': 'برجاء تحديث هذه الخيارات قبل إضافة أى منتج',
    'product_code_name': 'صنف (كود - اسم)',
    'unit_price_no_tax': 'سعر الوحدة بدون ضريبة',
    'unit_price_with_tax': 'سعر الوحدة بالضريبة',
    'sold_quantity': 'الكمية المباعه',
    'total_no_tax': 'الاجمالي بدون ضريبة',
    'total_product_sr': 'اجمالي الصنف (SR)',
    'discount': 'الخصم',
    'sale_status': 'حالة فاتورة المبيعات *',
    'due_date': 'أجل الاستحقاق',
    'paid_amount': 'المدفوع',
    'payment_by': 'الدفع بواسطة *',
    'add_more_payments': 'إضافة المزيد من المدفوعات',
    'sale_notes': 'ملاحظات فاتورة المبيعات',
    'complete_operation': 'اتمام العملية',
    'preview_invoice': 'معاينة الفاتورة',
    'reset_form': 'إعادة تعيين',
    'operation_completed_successfully': 'تم إتمام العملية بنجاح!',
    'preview_invoice_msg': 'جاري تجهيز معاينة الفاتورة...',
    'network': 'شبكة',
    'cash': 'نقدي',
    'bank_transfer': 'تحويل بنكي',
    'pos_quick': 'نقاط البيع',
    'invoices_a4': 'فواتير A4',
    'invoices_pos': 'فواتير POS',
    'new_sale': 'عملية بيع جديدة',
    'add_tax_invoice': 'إضافة فاتورة ضريبة',
    'add_simplified_tax_invoice': 'إضافة فاتورة ضريبة مبسطة',
    'add_sale_csv': 'إضافة بيع من ملف CSV',
    'gift_cards': 'قائمة كروت الهدايا',
    'quotes': 'عروض الأسعار',
    'quotes_list': 'قائمة عروض الأسعار',
    'add_quote': 'إضافة عرض سعر',
    'purchases': 'المشتريات',
    'purchases_list': 'قائمة المشتريات',
    'purchases_all_branches': 'المشتريات (جميع الفروع)',
    'supplier': 'مورد',
    'purchase_status': 'حالة عملية الشراء',
    'paid': 'مدفوع',
    'balance': 'الرصيد',
    'payment_status': 'حالة الدفع',
    'purchase_invoice_type': 'نوع فاتورة المشتريات',
    'all': 'الكل',
    'purchase_details': 'تفاصيل عملية الشراء',
    'add_purchase': 'إضافة عملية شراء',
    'add_purchase_csv': 'إضافة شراء من ملف CSV',
    'coming_soon': 'قريباً',
    'expenses_list': 'قائمة المصروفات',
    'add_expense': 'إضافة المصروفات',
    'transfers': 'تحويل المخزون',
    'transfers_list': 'قائمة تحويل المخزون',
    'add_transfer': 'إضافة تحويل مخزون',
    'add_transfer_csv': 'إضافة نقل من ملف CSV',
    'users': 'المستخدمين',
    'users_list': 'قائمة المستخدمين',
    'add_user': 'إضافة مستخدم',
    'pos_devices': 'أجهزة اصدار الفواتير',
    'add_device': 'إضافة جهاز',
    'customers': 'العملاء',
    'customers_list': 'قائمة العملاء',
    'add_customer': 'اضافة عميل',
    'please_select_customer_type': 'برجاء تحديد نوع العميل',
    'not_registered_tax': 'غير مسجل بالضريبة',
    'registered_tax': 'مسجل بالضريبة',
    'customer_group': 'مجموعة العملاء *',
    'pricing_group_label': 'مجموعة التسعيرة',
    'pricing_group': 'مجموعة التسعيرة',
    'tax_number': 'الرقم الضريبي',
    'actual_balance': 'الرصيد الفعلي',
    'total_points': 'إجمالي النقاط المكتسبة',
    'code': 'كود',
    'customer_name_label': 'اسم العميل *',
    'phone': 'هاتف',
    'email_address': 'عنوان البريد الإلكتروني',
    'commercial_register': 'السجل التجاري',
    'opening_balance': 'رصيد افتتاحي *( المديونية بالسالب)',
    'credit_limit': 'الحد الائتماني *',
    'stop_sale_if_overdue': 'ايقاف البيع في حالة وجود مبالغ مستحقة',
    'add_customer_button': 'اضافة عميل',
    'deposits_list': 'قائمة الايداعات',
    'add_deposit': 'اضافة ايداع',
    'discounts_list': 'قائمة الخصومات',
    'add_discount': 'اضافة خصم',
    'edit_customer': 'تعديل العميل',
    'suppliers': 'الموردين',
    'suppliers_list': 'قائمة الموردين',
    'add_supplier': 'إضافة مورد',
    'banks': 'البنوك',
    'banks_list': 'قائمة البنوك',
    'add_bank': 'إضافة بنك',
    'external_transfers': 'تحويلات بنكية خارجية',
    'add_external_transfer': 'إضافة تحويل بنكي خارجي',
    'internal_transfers': 'تحويلات بنكية داخلية',
    'bonds': 'السندات',
    'receipt_bonds': 'سندات قبض نقدية',
    'add_receipt_bond': 'إضافة سند قبض نقدية',
    'payment_bonds': 'سندات صرف نقدية',
    'add_payment_bond': 'إضافة سند صرف نقدية',
    'deposit_bonds': 'سندات ايداع نقدية في البنك',
    'add_deposit_bond': 'إضافة سند ايداع نقدية في البنك',
    'withdrawal_bonds': 'سحوبات النقدية من البنك',
    'add_withdrawal_bond': 'إضافة سند سحب نقدية من البنك',
    'settings': 'الإعدادات',
    'system_settings': 'إعدادات النظام',
    'payment_companies': 'شركات الدفع',
    'payment_methods': 'طرق الدفع',
    'pos_settings': 'إعدادات نقاط البيع',
    'delivery_companies': 'شركات التوصيل',
    'promotions': 'العروض الترويجية',
    'change_logo': 'تغيير اللوجو',
    'currencies': 'العملات',
    'customer_groups': 'مجموعات العملاء',
    'pricing_groups': 'مجموعات التسعيرة',
    'basic_categories': 'التصنيفات الأساسية',
    'expense_categories': 'تصنيفات المصروفات',
    'brands': 'الماركات',
    'variants': 'المتغيرات',
    'tax_rates': 'أسعار الضريبة',
    'regions': 'المناطق',
    'delegates': 'المندوبين و الموظفين',
    'tables': 'الطاولات',
    'branches': 'الفروع',
    'production_machines': 'ماكينات الانتاج',
    'group_permissions': 'ضوابط وصلاحيات المجموعة',
    'site_logins': 'تسجيلات دخول الموقع',
    'reports': 'التقارير',
    'notifications': 'الإشعارات',
    'no_notifications': 'لا يوجد إشعارات جديدة',
    'language': 'اللغة',
    'arabic': 'العربية',
    'english': 'English',
    'profile': 'الملف الشخصي',
    'logout': 'تسجيل الخروج',
    'search': 'بحث...',
    'welcome': 'أهلاً بك',
    'admin': 'مدير النظام',
    'view_all': 'عرض الكل',
    'new_order': 'طلب جديد',
    'order_desc': 'تم استلام طلب جديد #1234',
    'system_update': 'تحديث النظام',
    'update_desc': 'تم تحديث النظام بنجاح',
    'low_stock': 'تنبيه مخزون',
    'stock_desc': 'المنتج X وصل للحد الأدنى',
    // Dashboard
    'loading_data': 'جاري تحميل البيانات...',
    'renewal_request_sent': 'تم الاشتراك بنجاح',
    'welcome_admin': 'أهلاً بك، مدير النظام',
    'total_operations_date': 'إجمالي العمليات لتاريخ',
    'renew_subscription_days': 'تجديد الإشتراك - الأيام المتبقية: 937 يوم',
    'total_sales': 'إجمالي المبيعات',
    'currency_sar': 'ر.س',
    'total_purchases': 'إجمالي المشتريات',
    'net_profit': 'صافي الأرباح',
    'total_receivables': 'إجمالي المستحقات',
    'chart_overview': 'نظرة عامة على الرسم البياني',
    'last_6_months': 'آخر 6 أشهر',
    'last_year': 'آخر سنة',
    'recent_transactions': 'أحدث العمليات',
    // Login
    'login': 'تسجيل الدخول',
    'welcome_login_message': 'مرحبا بك، سجل الدخول للمتابعة',
    'email': 'البريد الإلكتروني',
    'password': 'كلمة المرور',
    'remember_me': 'تذكرني',
    'forgot_password': 'نسيت كلمة المرور؟',
    'login_button': 'دخول',
    'login_footer_text': 'ما تحتاجه لإدارة اعمالك بكل سهولة فى مكان واحد',
    'login_loading': 'جاري تسجيل الدخول...',
    'login_error': 'فشل تسجيل الدخول. تحقق من البريد وكلمة المرور.',
    'login_network_error': 'خطأ في الاتصال بالخادم. تحقق من الإنترنت أو حاول لاحقاً.',
    'copyright_text': 'takamul V1.10 جميع الحقوق محفوظة @2026',
    // Recent Transactions
    'stock_transfers': 'تحويل المخزون',
    'id': '#',
    'date': 'التاريخ',
    'invoice_no': 'رقم الفاتورة',
    'ref_no': 'الرقم المرجعي',
    'customer': 'العميل',
    'status': 'الحالة',
    'total': 'المجموع',
    'general_person': 'شخص عام',
    'completed': 'مكتملة',
    'no_data_display': 'لا توجد بيانات للعرض حالياً في هذا القسم',
    // Forgot Password
    'password_recovery': 'استعادة كلمة المرور',
    'password_recovery_desc': 'الرجاء إدخال البريد الإلكتروني أو اسم المستخدم المرتبط بحسابك لاستلام رابط إعادة تعيين كلمة المرور.',
    'email_username': 'البريد الإلكتروني / اسم المستخدم',
    'send_recovery_link': 'إرسال رابط الاستعادة',
    'sent_successfully': 'تم الإرسال بنجاح',
    'recovery_email_sent_desc': 'إذا كان هذا الحساب موجوداً، فقد تم إرسال تعليمات استعادة كلمة المرور إلى بريدك الإلكتروني.',
    'back_to_login': 'العودة لتسجيل الدخول',
    'enter_otp': 'أدخل رمز التحقق',
    'otp_sent_to_email': 'تم إرسال رمز التحقق إلى بريدك الإلكتروني.',
    'otp_code': 'رمز التحقق (OTP)',
    'verify_otp': 'تحقق من الرمز',
    'new_password': 'كلمة المرور الجديدة',
    'confirm_password': 'تأكيد كلمة المرور',
    'reset_password_title': 'إعادة تعيين كلمة المرور',
    'reset_password_button': 'تعيين كلمة المرور',
    'reset_password_success': 'تم تغيير كلمة المرور بنجاح.',
    'forgot_password_error': 'فشل طلب استعادة كلمة المرور.',
    'error_validation': 'حدث خطأ في التحقق من البيانات. تأكد من صحة البيانات المدخلة أو صلاحية الرمز.',
    'otp_error': 'رمز التحقق غير صحيح أو منتهي.',
    'reset_password_error': 'فشل إعادة تعيين كلمة المرور.',
    // Products List
    'home': 'البداية',
    'products_all_branches': 'الأصناف (جميع الفروع)',
    'products_table_desc': 'الرجاء استخدام الجدول أدناه للتنقل أو تصفية النتائج.',
    'update_prices': 'تحديث الأسعار',
    'delete': 'حذف',
    'confirm_delete_count': 'هل أنت متأكد من حذف',
    'items_question': 'عنصر؟',
    'confirm_delete_product': 'هل أنت متأكد من حذف هذا الصنف؟',
    'update_prices_title': 'تحديث الأسعار',
    'update_prices_desc': 'يرجى رفع ملف Excel يحتوي على الأسعار الجديدة',
    'choose_file': 'اختر ملف',
    'show': 'اظهر',
    'search_placeholder': 'اكتب ما تريد ان تبحث عنه',
    'image': 'صورة',
    'product_code': 'كود الصنف',
    'name': 'اسم',
    'brand': 'الماركة',
    'agent': 'الوكيل',
    'main_categories': 'التصنيفات الرئيسية',
    'cost': 'التكلفة',
    'selling_price': 'سعر البيع',
    'quantity': 'كمية',
    'unit': 'وحدة',
    'stock_alerts': 'تنبيهات بكميات المخزون',
    'actions': 'الإجراءات',
    'duplicate_group': 'تكرار التصنيف',
    'delete_group': 'حذف التصنيف',
    'duplicate_product': 'تكرار الصنف',
    'edit_product': 'تعديل الصنف',
    'print_barcode_labels': 'طباعة باركود - الملصقات',
    'branch_prices': 'الأسعار في الفروع',
    'branch_prices_soon': 'ميزة الأسعار في الفروع ستتوفر قريباً',
    'product_available_in_branch': 'الصنف متاح في هذا الفرع',
    'internal_units_count': 'عدد الوحدات الداخلية',
    'wholesale_price': 'سعر الجملة',
    'edit_product_btn': 'تعديل الصنف',
    'view_quote': 'عرض سعر',
    'edit_quote_action': 'تعديل عرض السعر',
    'create_sales_invoice': 'إنشاء فاتورة مبيعات',
    'create_purchase_invoice': 'إنشاء فاتورة مشتريات',
    'download_pdf_quote': 'تحميل بصيغة PDF',
    'send_email_quote': 'ارسال عرض السعر بالبريد الالكتروني',
    'delete_quote_action': 'حذف عرض السعر',
    'quote_no': 'رقم العرض',
    'quote_no_title': 'رقم عرض السعر',
    'description': 'وصف',
    'no_categories': 'لا توجد تصنيفات',
    'item_no': 'م',
    'data_entry': 'مدخل البيانات',
    'updated_by': 'تحديث قام به',
    'updated_at': 'تم التحديث في',
    'sold_qty': 'الكمية المباعة',
    'total_no_vat': 'الاجمالي بدون ضريبة',
    'unit_price_no_vat': 'سعر الوحدة بدون ضريبة',
    'unit_price_with_vat': 'سعر الوحدة بالضريبة',
    'product_total': 'اجمالي الصنف',
    'attach_documents': 'إرفاق المستندات',
    'complete_process': 'اتمام العملية',
    'all_branches': 'جميع الفروع',
    'shipping': 'الشحن',
    'view': 'عرض',
    'pdf_btn': 'PDF',
    'email_btn': 'البريد الإلكتروني',
    'edit_btn': 'تعديل',
    'delete_btn': 'حذف',
    'edit': 'تعديل',
    'select_customer': 'اختر عميل',
    'delete_product': 'حذف الصنف',
    'showing_records': 'عرض',
    'to': 'إلى',
    'of': 'من',
    'records': 'سجلات',
    'previous': 'سابق',
    'next': 'التالي',
    'copy_suffix': '(نسخة)',
    // Add Product
    'add_product_title': 'إضافة الصنف',
    'add_product_desc': 'برجاء ادخال المعلومات أدناه. تسميات الحقول التي تحمل علامة * هي حقول اجبارية .',
    'product_type': 'نوع الصنف *',
    'general': 'عام',
    'service': 'خدمي',
    'product_name': 'اسم الصنف *',
    'product_name_second_lang': 'اسم الصنف باللغة الثانية',
    'product_name_sec_lang': 'اسم الصنف باللغة الثانية',
    'product_name_third_lang': 'اسم الصنف باللغة الثالثة',
    'product_code_required': 'كود الصنف *',
    'generate_code': 'توليد كود',
    'barcode_reader_hint': 'يمكن إستخدام قاريء الباركود أيضاً',
    'alt_code': 'كود بديل',
    'select_brand': 'اختر الماركة',
    'product_cost': 'تكلفة الصنف *',
    'product_price': 'سعر الصنف *',
    'max_order_qty': 'أقصى كمية للطلب *',
    'reorder_point': 'حد الطلب',
    'has_variants_label': 'هذا الصنف لديها بدائل متعددة مثلا مقاسات متعددة و / أو الألوان',
    'main_categories_required': 'التصنيفات الرئيسية *',
    'select_main_categories': 'اختر التصنيفات الرئيسية',
    'sub_category': 'التصنيف الفرعي',
    'select_category_load': 'الرجاء تحديد الفئة للتحميل',
    'product_unit': 'وحدة الصنف *',
    'select_unit': 'اختر وحدة',
    'default_sale_unit': 'وحدة البيع الإفتراضية',
    'default_purchase_unit': 'وحدة الشراء الإفتراضية',
    'additional_units': 'وحدات اضافية',
    'list_price_branch_order_limit': 'مبلغ الليستة وحد الطلب للفروع',
    'branch_name': 'اسم الفرع',
    'list_amount': 'مبلغ اللسته',
    'stock_alerts_header': 'تنبيهات بكميات المخزون',
    'accuracy_solutions_company': 'شركة دقة الحلول',
    'product_availability_branches': 'إتاحية الصنف في الفروع',
    'status_header': 'الحالة',
    'yes': 'نعم',
    'no': 'لا',
    'product_image': 'صورة الصنف',
    'browse': 'استعراض ...',
    'product_gallery': 'كتالوج صور الصنف',
    'stock_item': 'صنف مخزون',
    'hide_pos': 'اخفاء في شاشة نقاط البيع',
    'featured_product': 'متميز (ضعه في رئسية المتجر إن كان مفعل)',
    'new_arrival': 'وصل حديثا',
    'hide_store': 'اخفاء في شاشة المتجر',
    'product_details': 'تفاصيل الصنف',
    // Import Products
    'import_products_csv': 'إضافة الأصناف من قبل CSV',
    'download_sample_file': 'تحميل عينة الملف',
    'csv_instruction_1': 'ينبغي أن يظل السطر الأول في ملف CSV الذي يتم تحميله كما هو. يرجى عدم تغيير ترتيب الأعمدة.',
    'csv_instruction_2': 'ترتيب الأعمدة الصحيح...',
    'csv_instruction_3': 'يجب تحميل الصور في المجلد assets/uploads/ folder and thumbnails بنفس الاسم المذكور بملف CSV assets/uploads/thumbs/',
    'csv_instruction_4': 'سيقوم النظام بفحص اذا كان الكود خاص بأي من الأصناف المخزنة . غير ذلك سيتم اضافة الصنف كصنف جديد',
    'upload_file': 'تحميل الملف *',
    'import': 'استيراد',
    // Print Barcode
    'print_barcode_labels_title': 'طباعة باركود - الملصقات',
    'sales_all_branches': 'المبيعات (جميع الفروع)',
    'sales_table_desc': 'البيانات الظاهرة في آخر 30 يوم . برجاء استخدام النموذج لإظهار مزيد من النتائج',
    'grand_total': 'المجموع الكلي',
    'remaining_amount': 'المبلغ المتبقي',
    'payment_type': 'نوع الدفع',
    'returned': 'رجيع',
    'mada': 'مدى',
    'view_invoice': 'عرض الفاتورة',
    'edit_sale': 'تعديل البيع',
    'return_sale': 'إرجاع البيع',
    'delete_sale': 'حذف البيع',
    'total_records': 'إجمالي السجلات',
    'invoice_details': 'تفاصيل فاتورة المبيعات',
    'duplicate_sale': 'تكرار فاتورة المبيعات',
    'view_payments': 'عرض المدفوعات',
    'add_payment': 'إضافة الدفع',
    'store_bond': 'سند مخزني',
    'claim_bond': 'سند مطالبة',
    'add_delivery': 'إضافة تسليم',
    'download_pdf': 'تحميل بصيغة PDF',
    'download_excel': 'تحميل كملف إكسل',
    'download_csv': 'تحميل بصيغة CSV',
    'send_email': 'ارسال الفاتورة بالبريد الالكتروني',
    'send_whatsapp': 'إرسال الفاتورة عبر الواتس',
    'release_bond': 'سند فسخ',
    'edit_delegate': 'تعديل المندوب / الموظف',
    'gift_cards_list': 'قائمة كروت الهدايا',
    'add_gift_card': 'إضافة بطاقة هدية',
    'delete_gift_cards': 'حذف كروت الهدايا',
    'card_no': 'رقم البطاقة',
    'value': 'القيمة',
    'notes': 'ملاحظات',
    'expiry_date': 'تاريخ الإنتهاء',
    'walk_in_customer': 'عميل افتراضي',
    'use_employee_points_program': 'استخدام برنامج نقاط الموظف',
    'gift_cards_table_desc': 'الرجاء استخدام الجدول أدناه للتنقل أو تصفية النتائج.',
    'no_data_in_table': 'لا توجد بيانات في الجدول',
    'payment_view_title': 'عرض المدفوعات (بيع المرجع: {ref})',
    'store_bond_title': 'سند مخزني',
    'claim_letter_title': 'نموذج خطاب مطالبة مالية',
    'delivery_title': 'إضافة تسليم',
    'delivery_status': 'الحالة *',
    'delivery_ref': 'الرقم المرجعي للتسليم',
    'sale_ref': 'الرقم المرجعي للبيع *',
    'address': 'العنوان *',
    'attachments': 'ملحقات',
    'note': 'مذكرة',
    'add_delivery_btn': 'إضافة تسليم',
    'edit_payment': 'تعديل الدفع',
    'edit_payment_desc': 'برجاء ادخال المعلومات أدناه. تسميات الحقول التي تحمل علامة * هي حقول اجبارية .',
    'payment_ref': 'الرقم المرجعي',
    'receipt_bond': 'سند قبض',
    'received_from': 'استلمنا من السيد',
    'amount_of': 'مبلغ وقدره',
    'for_payment': 'وذلك مقابل',
    'seal_signature': 'الختم أو التوقيع',
    'receiver': 'المستلم',
    'email_sent_success': 'تم ارسال الايميل بنجاح',
    'print_barcode_desc': 'يمكنك زيارة التصنيفات الأساسية, التصنيفات الفرعية, مشتريات و تحويل المخزون لإضافة الأصناف لقائمة الطباعة',
    'add_product_label': 'إضافة الصنف',
    'activity_name': 'اسم النشاط',
    'expiry': 'انتهاء',
    'production': 'انتاج',
    'product_name_code': 'اسم الصنف (كود الصنف)',
    'no_products_added': 'لا توجد أصناف مضافة',
    'print_method': 'طريقة الطباعة *',
    'continuous_print': 'طباعة مستمرة(طابعة باركود)',
    'a4_paper': 'ورقة A4',
    'width': 'العرض',
    'mm': 'مللي',
    'height': 'الإرتفاع',
    'barcode_height': 'ارتفاع أعمدة الباركود',
    'px': 'px',
    'barcode_orientation': 'اتجاه أعمدة الباركود',
    'vertical': 'عمودي',
    'horizontal': 'أفقي',
    'check_promo_price': 'فحص سعر الترويج',
    'print': 'طباعة',
    'company_name': 'اسم الشركة',
    'tax_inclusive': 'شامل ضريبة',
    'font_formatting': 'تنسيق الخطوط',
    'format_product_name': 'تنسيق اسم الصنف',
    'format_activity_name': 'تنسيق اسم النشاط',
    'format_dates': 'تنسيق تاريخ الانتاج والإنتهاء',
    'format_price': 'تنسيق السعر',
    'font_size': 'حجم الخط',
    'spacing': 'التباعد',
    'font_color': 'لون الخط',
    'bg_color': 'لون الخلفية',
    'update': 'تحديث',
    'light_mode': 'الوضع الفاتح',
    'dark_mode': 'الوضع الداكن',
    'filter_results': 'تصفية النتائج',
    'from_date': 'من تاريخ',
    'to_date': 'الى تاريخ',
    'export_to_excel': 'تصدير إلى ملف Excel',
    'export_to_pdf': 'تصدير إلى ملف pdf',
    'delete_selected_items': 'حذف الأصناف المحددة',
    'supplier_name': 'اسم المورد',
    'please_enter_info_below': 'برجاء ادخال المعلومات أدناه. تسميات الحقول التي تحمل علامة * هي حقول اجبارية .',
    'amount_due_to_supplier': 'المبلغ المستحق للمورد',
    'supplier_added_successfully': 'تم إضافة المورد بنجاح',
    'supplier_updated_successfully': 'تم تحديث بيانات المورد بنجاح',
    'supplier_deleted_successfully': 'تم حذف المورد بنجاح',
    'please_enter_supplier_name': 'الرجاء إدخال اسم المورد',
    'confirm_delete_supplier': 'هل تريد حذف هذا المورد؟',
    'commercial_registration': 'السجل التجاري',
    'operation_failed': 'فشلت العملية',
    'loading': 'جاري...',
    'cancel': 'إلغاء',
    'edit_supplier': 'تعديل مورد'
  },
  en: {
    'dashboard': 'Dashboard',
    'products': 'Products',
    'products_list': 'Products List',
    'add_product': 'Add Product',
    'import_products': 'Import Products',
    'print_barcode': 'Print Barcode',
    'quantity_adjustments': 'Quantity Adjustments',

    'groups': 'Categories',
    'add_new_group': 'Add New Category',
    'units': 'Units',
    'group_code': 'Category Code',
    'group_name': 'Category Name',
    'group_name_secondary_lang': 'Category Name in Second Language',
    'group_image': 'Category Image',
    'add_new_unit': 'Add New Unit',
    'unit_code': 'Unit Code',
    'unit_name': 'Unit Name',
    'sales': 'Sales',
    'all_sales': 'All Sales',
    'sales_a4_quick': 'A4 Sales',
    'a4_sales_title': 'Add A4 Sales',
    'add_sale_operation': 'Add Sale Operation',
    'cashier': 'Cashier',
    'branch': 'Branch',
    'customer_label': 'Customer',
    'delegate_employee': 'Delegate / Employee',
    'po_number': 'P.O. Number',
    'project_name': 'Project Name',
    'please_add_items': 'Please add items',
    'update_options_before_adding': 'Please update these options before adding any product',
    'product_code_name': 'Product (Code - Name)',
    'unit_price_no_tax': 'Unit Price (No Tax)',
    'unit_price_with_tax': 'Unit Price (With Tax)',
    'sold_quantity': 'Sold Quantity',
    'total_no_tax': 'Total (No Tax)',
    'total_product_sr': 'Total Product (SR)',
    'discount': 'Discount',
    'sale_status': 'Sale Status *',
    'due_date': 'Due Date',
    'paid_amount': 'Paid Amount',
    'payment_by': 'Payment By *',
    'add_more_payments': 'Add More Payments',
    'sale_notes': 'Sale Notes',
    'complete_operation': 'Complete Operation',
    'preview_invoice': 'Preview Invoice',
    'reset_form': 'Reset',
    'operation_completed_successfully': 'Operation completed successfully!',
    'preview_invoice_msg': 'Preparing invoice preview...',
    'network': 'Network',
    'cash': 'Cash',
    'bank_transfer': 'Bank Transfer',
    'pos_quick': 'POS',
    'invoices_a4': 'A4 Invoices',
    'invoices_pos': 'POS Invoices',
    'new_sale': 'New Sale',
    'add_tax_invoice': 'Add Tax Invoice',
    'add_simplified_tax_invoice': 'Add Simplified Tax Invoice',
    'add_sale_csv': 'Add Sale from CSV',
    'gift_cards': 'Gift Cards',
    'quotes': 'Quotes',
    'quotes_list': 'Quotes List',
    'add_quote': 'Add Quote',
    'purchases': 'Purchases',
    'purchases_list': 'Purchases List',
    'purchases_all_branches': 'Purchases (All Branches)',
    'supplier': 'Supplier',
    'purchase_status': 'Purchase Status',
    'paid': 'Paid',
    'balance': 'Balance',
    'payment_status': 'Payment Status',
    'purchase_invoice_type': 'Purchase Invoice Type',
    'all': 'All',
    'purchase_details': 'Purchase Details',
    'add_purchase': 'Add Purchase',
    'add_purchase_csv': 'Add Purchase from CSV',
    'coming_soon': 'Coming soon.',
    'expenses_list': 'Expenses List',
    'add_expense': 'Add Expense',
    'transfers': 'Stock Transfers',
    'transfers_list': 'Transfers List',
    'add_transfer': 'Add Transfer',
    'add_transfer_csv': 'Add Transfer from CSV',
    'users': 'Users & Devices',
    'users_list': 'Users List',
    'add_user': 'Add User',
    'pos_devices': 'POS Devices',
    'add_device': 'Add Device',
    'customers': 'Customers',
    'customers_list': 'Customers List',
    'add_customer': 'Add Customer',
    'please_select_customer_type': 'Please select customer type',
    'not_registered_tax': 'Not registered for tax',
    'registered_tax': 'Registered for tax',
    'customer_group': 'Customer Group *',
    'pricing_group_label': 'Pricing Group',
    'pricing_group': 'Pricing Group',
    'tax_number': 'Tax Number',
    'actual_balance': 'Actual Balance',
    'total_points': 'Total Points',
    'code': 'Code',
    'customer_name_label': 'Customer Name *',
    'phone': 'Phone',
    'email_address': 'Email Address',
    'commercial_register': 'Commercial Register',
    'opening_balance': 'Opening Balance * (Negative for debt)',
    'credit_limit': 'Credit Limit *',
    'stop_sale_if_overdue': 'Stop sale if there are overdue amounts',
    'add_customer_button': 'Add Customer',
    'deposits_list': 'Deposits List',
    'add_deposit': 'Add Deposit',
    'discounts_list': 'Discounts List',
    'add_discount': 'Add Discount',
    'edit_customer': 'Edit Customer',
    'suppliers': 'Suppliers',
    'suppliers_list': 'Suppliers List',
    'add_supplier': 'Add Supplier',
    'banks': 'Banks',
    'banks_list': 'Banks List',
    'add_bank': 'Add Bank',
    'external_transfers': 'External Transfers',
    'add_external_transfer': 'Add External Transfer',
    'internal_transfers': 'Internal Transfers',
    'bonds': 'Bonds',
    'receipt_bonds': 'Receipt Bonds',
    'add_receipt_bond': 'Add Receipt Bond',
    'payment_bonds': 'Payment Bonds',
    'add_payment_bond': 'Add Payment Bond',
    'deposit_bonds': 'Deposit Bonds',
    'add_deposit_bond': 'Add Deposit Bond',
    'withdrawal_bonds': 'Withdrawal Bonds',
    'add_withdrawal_bond': 'Add Withdrawal Bond',
    'settings': 'Settings',
    'system_settings': 'System Settings',
    'payment_companies': 'Payment Companies',
    'payment_methods': 'Payment Methods',
    'pos_settings': 'POS Settings',
    'delivery_companies': 'Delivery Companies',
    'promotions': 'Promotions',
    'change_logo': 'Change Logo',
    'currencies': 'Currencies',
    'customer_groups': 'Customer Groups',
    'pricing_groups': 'Pricing Groups',
    'basic_categories': 'Basic Categories',
    'expense_categories': 'Expense Categories',
    'brands': 'Brands',
    'variants': 'Variants',
    'tax_rates': 'Tax Rates',
    'regions': 'Regions',
    'delegates': 'Delegates & Employees',
    'tables': 'Tables',
    'branches': 'Branches',
    'production_machines': 'Production Machines',
    'group_permissions': 'Group Permissions',
    'site_logins': 'Site Logins',
    'reports': 'Reports',
    'notifications': 'Notifications',
    'no_notifications': 'No new notifications',
    'language': 'Language',
    'arabic': 'Arabic',
    'english': 'English',
    'profile': 'Profile',
    'logout': 'Logout',
    'search': 'Search...',
    'welcome': 'Welcome',
    'admin': 'Admin',
    'view_all': 'View All',
    'new_order': 'New Order',
    'order_desc': 'New order received #1234',
    'system_update': 'System Update',
    'update_desc': 'System updated successfully',
    'low_stock': 'Stock Alert',
    'stock_desc': 'Product X reached minimum stock',
    // Dashboard
    'loading_data': 'Loading data...',
    'renewal_request_sent': 'Subscription successful',
    'welcome_admin': 'Welcome, System Admin',
    'total_operations_date': 'Total operations for date',
    'renew_subscription_days': 'Renew Subscription - Days remaining: 937 days',
    'total_sales': 'Total Sales',
    'currency_sar': 'SAR',
    'total_purchases': 'Total Purchases',
    'net_profit': 'Net Profit',
    'total_receivables': 'Total Receivables',
    'chart_overview': 'Chart Overview',
    'last_6_months': 'Last 6 Months',
    'last_year': 'Last Year',
    'recent_transactions': 'Recent Transactions',
    // Login
    'login': 'Login',
    'welcome_login_message': 'Welcome, login to continue',
    'email': 'Email',
    'password': 'Password',
    'remember_me': 'Remember me',
    'forgot_password': 'Forgot password?',
    'login_button': 'Login',
    'login_footer_text': 'Everything you need to manage your business easily in one place',
    'login_loading': 'Logging in...',
    'login_error': 'Login failed. Please check your email and password.',
    'login_network_error': 'Connection error. Check your internet or try again later.',
    'copyright_text': 'takamul V1.10 All rights reserved @2026',
    // Recent Transactions
    'stock_transfers': 'Stock Transfers',
    'id': '#',
    'date': 'Date',
    'invoice_no': 'Invoice No',
    'ref_no': 'Reference No',
    'customer': 'Customer',
    'status': 'Status',
    'total': 'Total',
    'general_person': 'General Person',
    'completed': 'Completed',
    'no_data_display': 'No data to display in this section currently',
    // Forgot Password
    'password_recovery': 'Password Recovery',
    'password_recovery_desc': 'Please enter your email or username associated with your account to receive a password reset link.',
    'email_username': 'Email / Username',
    'send_recovery_link': 'Send Recovery Link',
    'sent_successfully': 'Sent Successfully',
    'recovery_email_sent_desc': 'If this account exists, password recovery instructions have been sent to your email.',
    'back_to_login': 'Back to Login',
    'enter_otp': 'Enter verification code',
    'otp_sent_to_email': 'A verification code has been sent to your email.',
    'otp_code': 'Verification code (OTP)',
    'verify_otp': 'Verify code',
    'new_password': 'New password',
    'confirm_password': 'Confirm password',
    'reset_password_title': 'Reset password',
    'reset_password_button': 'Set password',
    'reset_password_success': 'Password changed successfully.',
    'forgot_password_error': 'Password recovery request failed.',
    'error_validation': 'One or more validation errors occurred. Please check the entered data or reset token.',
    'otp_error': 'Invalid or expired verification code.',
    'reset_password_error': 'Password reset failed.',
    // Products List
    'home': 'Home',
    'products_all_branches': 'Products (All Branches)',
    'products_table_desc': 'Please use the table below to navigate or filter results.',
    'update_prices': 'Update Prices',
    'delete': 'Delete',
    'confirm_delete_count': 'Are you sure you want to delete',
    'items_question': 'items?',
    'confirm_delete_product': 'Are you sure you want to delete this product?',
    'update_prices_title': 'Update Prices',
    'update_prices_desc': 'Please upload an Excel file containing the new prices',
    'choose_file': 'Choose File',
    'show': 'Show',
    'search_placeholder': 'Type what you want to search for',
    'image': 'Image',
    'product_code': 'Product Code',
    'name': 'Name',
    'brand': 'Brand',
    'agent': 'Agent',
    'main_categories': 'Main Categories',
    'cost': 'Cost',
    'selling_price': 'Selling Price',
    'quantity': 'Quantity',
    'unit': 'Unit',
    'stock_alerts': 'Stock Alerts',
    'actions': 'Actions',
    'duplicate_group': 'Duplicate Category',
    'delete_group': 'Delete Category',
    'duplicate_product': 'Duplicate Product',
    'edit_product': 'Edit Product',
    'print_barcode_labels': 'Print Barcode - Labels',
    'branch_prices': 'Branch Prices',
    'branch_prices_soon': 'Branch prices feature will be available soon',
    'product_available_in_branch': 'Product available in this branch',
    'internal_units_count': 'Internal Units Count',
    'wholesale_price': 'Wholesale Price',
    'edit_product_btn': 'Edit Product',
    'view_quote': 'View Quote',
    'edit_quote_action': 'Edit Quote',
    'create_sales_invoice': 'Create Sales Invoice',
    'create_purchase_invoice': 'Create Purchase Invoice',
    'download_pdf_quote': 'Download PDF',
    'send_email_quote': 'Send Quote via Email',
    'delete_quote_action': 'Delete Quote',
    'quote_no': 'Quote No',
    'quote_no_title': 'Quote Number',
    'description': 'Description',
    'no_categories': 'No categories available',
    'item_no': 'No',
    'data_entry': 'Data Entry',
    'updated_by': 'Updated By',
    'updated_at': 'Updated At',
    'sold_qty': 'Sold Qty',
    'total_no_vat': 'Total (No VAT)',
    'unit_price_no_vat': 'Unit Price (No VAT)',
    'unit_price_with_vat': 'Unit Price (With VAT)',
    'product_total': 'Product Total',
    'attach_documents': 'Attach Documents',
    'complete_process': 'Complete Process',
    'all_branches': 'All Branches',
    'shipping': 'Shipping',
    'view': 'View',
    'pdf_btn': 'PDF',
    'email_btn': 'Email',
    'edit_btn': 'Edit',
    'delete_btn': 'Delete',
    'edit': 'Edit',
    'select_customer': 'Select Customer',
    'delete_product': 'Delete Product',
    'showing_records': 'Showing',
    'to': 'to',
    'of': 'of',
    'records': 'records',
    'previous': 'Previous',
    'next': 'Next',
    'copy_suffix': '(Copy)',
    // Add Product
    'add_product_title': 'Add Product',
    'add_product_desc': 'Please enter the information below. Fields marked with * are mandatory.',
    'product_type': 'Product Type',
    'general': 'General',
    'service': 'Service',
    'product_name': 'Product Name',
    'product_name_second_lang': 'Product Name in Second Language',
    'product_name_sec_lang': 'Product Name in Second Language',
    'product_name_third_lang': 'Product Name in Third Language',
    'product_code_required': 'Product Code *',
    'generate_code': 'Generate Code',
    'barcode_reader_hint': 'Barcode reader can also be used',
    'alt_code': 'Alternative Code',
    'select_brand': 'Select Brand',
    'product_cost': 'Product Cost',
    'product_price': 'Product Price',
    'max_order_qty': 'Max Order Quantity',
    'reorder_point': 'Reorder Point',
    'has_variants_label': 'This product has multiple variants e.g. multiple sizes and/or colors',
    'main_categories_required': 'Main Categories *',
    'select_main_categories': 'Select Main Categories',
    'sub_category': 'Sub Category',
    'select_category_load': 'Please select category to load',
    'product_unit': 'Product Unit',
    'select_unit': 'Select Unit',
    'default_sale_unit': 'Default Sale Unit',
    'default_purchase_unit': 'Default Purchase Unit',
    'additional_units': 'Additional Units',
    'list_price_branch_order_limit': 'List Price & Order Limit for Branches',
    'branch_name': 'Branch Name',
    'list_amount': 'List Amount',
    'stock_alerts_header': 'Stock Alerts',
    'accuracy_solutions_company': 'Accuracy Solutions Company',
    'product_availability_branches': 'Product Availability in Branches',
    'status_header': 'Status',
    'yes': 'Yes',
    'no': 'No',
    'product_image': 'Product Image',
    'browse': 'Browse ...',
    'product_gallery': 'Product Gallery',
    'stock_item': 'Stock Item',
    'hide_pos': 'Hide in POS',
    'featured_product': 'Featured (Place in store home if enabled)',
    'new_arrival': 'New Arrival',
    'hide_store': 'Hide in Store',
    'product_details': 'Product Details',
    // Import Products
    'import_products_csv': 'Import Products via CSV',
    'download_sample_file': 'Download Sample File',
    'csv_instruction_1': 'The first line in the uploaded CSV file should remain as is. Please do not change the order of columns.',
    'csv_instruction_2': 'Correct column order...',
    'csv_instruction_3': 'Images must be uploaded to assets/uploads/ folder...',
    'csv_instruction_4': 'The system will check if the code belongs to any existing products. Otherwise, the product will be added as new.',
    'upload_file': 'Upload File',
    'import': 'Import',
    // Print Barcode
    'print_barcode_labels_title': 'Print Barcode - Labels',
    'sales_all_branches': 'Sales (All Branches)',
    'sales_table_desc': 'Data shown for the last 30 days. Please use the form to show more results',
    'grand_total': 'Grand Total',
    'remaining_amount': 'Remaining Amount',
    'payment_type': 'Payment Type',
    'returned': 'Returned',
    'mada': 'Mada',
    'view_invoice': 'View Invoice',
    'edit_sale': 'Edit Sale',
    'return_sale': 'Return Sale',
    'delete_sale': 'Delete Sale',
    'total_records': 'Total Records',
    'invoice_details': 'Invoice Details',
    'duplicate_sale': 'Duplicate Sale',
    'view_payments': 'View Payments',
    'add_payment': 'Add Payment',
    'store_bond': 'Store Bond',
    'claim_bond': 'Claim Bond',
    'add_delivery': 'Add Delivery',
    'download_pdf': 'Download PDF',
    'download_excel': 'Download Excel',
    'download_csv': 'Download CSV',
    'send_email': 'Send Invoice via Email',
    'send_whatsapp': 'Send Invoice via WhatsApp',
    'release_bond': 'Release Bond',
    'edit_delegate': 'Edit Delegate / Employee',
    'gift_cards_list': 'Gift Cards List',
    'add_gift_card': 'Add Gift Card',
    'delete_gift_cards': 'Delete Gift Cards',
    'card_no': 'Card No',
    'value': 'Value',
    'notes': 'Notes',
    'expiry_date': 'Expiry Date',
    'walk_in_customer': 'Walk-in Customer',
    'use_employee_points_program': 'Use Employee Points Program',
    'gift_cards_table_desc': 'Please use the table below to navigate or filter results.',
    'no_data_in_table': 'No data in table',
    'payment_view_title': 'View Payments (Sale Ref: {ref})',
    'store_bond_title': 'Store Bond',
    'claim_letter_title': 'Financial Claim Letter Template',
    'delivery_title': 'Add Delivery',
    'delivery_status': 'Status *',
    'delivery_ref': 'Delivery Reference',
    'sale_ref': 'Sale Reference *',
    'address': 'Address *',
    'attachments': 'Attachments',
    'note': 'Note',
    'add_delivery_btn': 'Add Delivery',
    'edit_payment': 'Edit Payment',
    'edit_payment_desc': 'Please enter the information below. Fields marked with * are mandatory.',
    'payment_ref': 'Reference No',
    'receipt_bond': 'Receipt Bond',
    'received_from': 'Received from',
    'amount_of': 'Amount of',
    'for_payment': 'For',
    'seal_signature': 'Seal or Signature',
    'receiver': 'Receiver',
    'email_sent_success': 'Email sent successfully',
    'print_barcode_desc': 'You can visit Main Categories, Sub Categories, Purchases and Stock Transfers to add products to the print list',
    'add_product_label': 'Add Product',
    'activity_name': 'Activity Name',
    'expiry': 'Expiry',
    'production': 'Production',
    'product_name_code': 'Product Name (Product Code)',
    'no_products_added': 'No products added',
    'print_method': 'Print Method',
    'continuous_print': 'Continuous Print (Barcode Printer)',
    'a4_paper': 'A4 Paper',
    'width': 'Width',
    'mm': 'mm',
    'height': 'Height',
    'barcode_height': 'Barcode Height',
    'px': 'px',
    'barcode_orientation': 'Barcode Orientation',
    'vertical': 'Vertical',
    'horizontal': 'Horizontal',
    'check_promo_price': 'Check Promo Price',
    'print': 'Print',
    'company_name': 'Company Name',
    'tax_inclusive': 'Tax Inclusive',
    'font_formatting': 'Font Formatting',
    'format_product_name': 'Format Product Name',
    'format_activity_name': 'Format Activity Name',
    'format_dates': 'Format Production & Expiry Dates',
    'format_price': 'Format Price',
    'font_size': 'Font Size',
    'spacing': 'Spacing',
    'font_color': 'Font Color',
    'bg_color': 'Background Color',
    'update': 'Update',
    'light_mode': 'Light Mode',
    'dark_mode': 'Dark Mode',
    'filter_results': 'Filter Results',
    'from_date': 'From Date',
    'to_date': 'To Date',
    'export_to_excel': 'Export to Excel file',
    'export_to_pdf': 'Export to pdf file',
    'delete_selected_items': 'Delete Selected Items',
    'supplier_name': 'Supplier Name',
    'please_enter_info_below': 'Please enter information below. Fields marked * are required.',
    'amount_due_to_supplier': 'Amount due to supplier',
    'supplier_added_successfully': 'Supplier added successfully',
    'supplier_updated_successfully': 'Supplier updated successfully',
    'supplier_deleted_successfully': 'Supplier deleted successfully',
    'please_enter_supplier_name': 'Please enter supplier name',
    'confirm_delete_supplier': 'Are you sure you want to delete this supplier?',
    'commercial_registration': 'Commercial Registration',
    'operation_failed': 'Operation failed',
    'loading': 'Loading...',
    'cancel': 'Cancel',
    'edit_supplier': 'Edit Supplier'
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const savedLang = localStorage.getItem('language');
    return (savedLang as Language) || 'ar';
  });

  const direction = language === 'ar' ? 'rtl' : 'ltr';

  useEffect(() => {
    const root = window.document.documentElement;
    root.setAttribute('lang', language);
    root.setAttribute('dir', direction);
    localStorage.setItem('language', language);
  }, [language, direction]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, direction, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
