import React, { createContext, useContext, useEffect, useState } from "react";
import { useSettings } from "./SettingsContext";

type Language = "ar" | "en";
type Direction = "rtl" | "ltr";

interface LanguageContextType {
  language: Language;
  direction: Direction;
  dir: Direction;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  ar: {
    confirm_delete_title: "تأكيد الحذف",
    confirm_delete_desc: "هل أنت متأكد من حذف هذا العنصر؟",
    confirm_delete_btn: "حذف",
    cancel: "إلغاء",
    dashboard: "الرئيسية",
    products: "الأصناف",
    products_list: "قائمة الأصناف",
    add_product: "اضافة الصنف",
    import_products: "استيراد الأصناف",
    print_barcode: "طباعة باركود - الملصقات",
    print_barcode_stickers: "طباعة باركود",
    quantity_adjustments: "التعديلات الكمية",

    groups: "التصنيفات",
    add_new_group: "إضافة تصنيفة جديده",
    units: "الوحدات",
    group_code: "كود التصنيف",
    group_name: "اسم التصنيف",
    group_name_secondary_lang: "اسم التصنيف باللغة الثانية",
    group_image: "صورة التصنيف",
    add_new_unit: "اضافة وحدة جديده",
    unit_code: "كود الوحده",
    unit_name: "اسم الوحده",
    sales: "المبيعات",
    all_sales: "جميع المبيعات",
    sales_a4_quick: "مبيعات A4",
    a4_sales_title: "إضافة مبيعات A4",
    add_sale_operation: "اضافة عمليه بيع",
    cashier: "كاشير",
    branch: "الفرع",
    customer_label: "عميل",
    delegate_employee: "المندوب / الموظف",
    po_number: "رقم أمر الشراء",
    project_name: "اسم المشروع",
    please_add_items: "الرجاء إضافة الأصناف",
    update_options_before_adding: "برجاء تحديث هذه الخيارات قبل إضافة أى منتج",
    product_code_name: "صنف (كود - اسم)",
    unit_price_no_tax: "سعر الوحدة بدون ضريبة",
    unit_price_with_tax: "سعر الوحدة بالضريبة",
    sold_quantity: "الكمية المباعه",
    total_no_tax: "الاجمالي بدون ضريبة",
    total_product_sr: "اجمالي الصنف (SR)",
    discount: "الخصم",
    sale_status: "حالة فاتورة المبيعات *",
    due_date: "أجل الاستحقاق",
    paid_amount: "المدفوع",
    payment_by: "الدفع بواسطة *",
    add_more_payments: "إضافة المزيد من المدفوعات",
    sale_notes: "ملاحظات فاتورة المبيعات",
    complete_operation: "اتمام العملية",
    preview_invoice: "معاينة الفاتورة",
    reset_form: "إعادة تعيين",
    close: "إغلاق",
    deposits_list: "قائمة الايداعات",
    add_deposit: "اضافة ايداع",
    discounts_list: "قائمة الخصومات",
    add_discount: "اضافة خصم",
    edit_customer: "تعديل العميل",
    operation_completed_successfully: "تم إتمام العملية بنجاح!",
    operation_added_successfully: "تمت إضافة العملية بنجاح",
    preview_invoice_msg: "جاري تجهيز معاينة الفاتورة...",
    network: "شبكة",
    cash: "نقدي",
    bank_transfer: "تحويل بنكي",
    pos_quick: "نقاط البيع",
    invoices_a4: "فواتير A4",
    invoices_pos: "فواتير POS",
    new_sale: "عملية بيع جديدة",
    add_tax_invoice: "إضافة فاتورة ضريبة",
    add_simplified_tax_invoice: "إضافة فاتورة ضريبة مبسطة",
    add_sale_csv: "إضافة بيع من ملف CSV",
    gift_cards: "قائمة كروت الهدايا",
    quotes: "عروض الأسعار",
    quotes_list: "قائمة عروض الأسعار",
    add_quote: "إضافة عرض سعر",
    purchases: "المشتريات",
    purchases_list: "قائمة المشتريات",
    purchases_all_branches: "المشتريات (جميع الفروع)",
    supplier: "مورد",
    purchase_status: "حالة عملية الشراء",
    paid: "مدفوع",
    balance: "الرصيد",
    payment_status: "حالة الدفع",
    purchase_invoice_type: "نوع فاتورة المشتريات",
    all: "الكل",
    purchase_details: "تفاصيل عملية الشراء",
    add_purchase: "إضافة عملية شراء",
    add_purchase_csv: "إضافة شراء من ملف CSV",
    expenses_list: "قائمة المصروفات",
    add_expense: "إضافة المصروفات",
    transfers: "تحويل المخزون",
    transfers_list: "قائمة تحويل المخزون",
    add_transfer: "إضافة تحويل مخزون",
    add_transfer_csv: "إضافة نقل من ملف CSV",
    users: "المستخدمين والأجهزة",
    users_list: "قائمة المستخدمين",
    user_groups: "مجموعات المستخدمين",
    add_user: "إضافة مستخدم",
    confirm_delete_user: "هل أنت متأكد من حذف هذا المستخدم؟",
    first_name: "الاسم الأول",
    last_name: "اللقب",
    gender: "النوع",
    male: "ذكر",
    female: "أنثى",
    company: "الشركة",
    username_email: "اسم المستخدم / البريد الإلكتروني",
    confirm_password: "تأكيد كلمة المرور",
    passwords_do_not_match: "كلمات المرور غير متطابقة",
    active: "نشط",
    inactive: "غير نشط",
    group: "مجموعة",
    default_payment_method: "طريقة الدفع الافتراضية",
    default_payment_company: "شركة الدفع الافتراضية",
    default_invoice_type: "نوع الفاتورة الافتراضي",
    notify_user_email: "إبلاغ المستخدم عن طريق البريد الإلكتروني",
    add_user_btn: "إضافة مستخدم",
    password_hint: "كلمة المرور يجب أن تحتوي حرف كبير أو رمز ورقم",
    pos_devices: "أجهزة اصدار الفواتير",
    add_device: "إضافة جهاز",
    additional_id: "المعرف الإضافي",
    confirm_delete_device: "هل أنت متأكد من حذف هذا الجهاز؟",
    customers: "العملاء",
    customers_list: "قائمة العملاء",
    add_customer: "اضافة عميل",
    please_select_customer_type: "برجاء تحديد نوع العميل",
    not_registered_tax: "غير مسجل بالضريبة",
    registered_tax: "مسجل بالضريبة",
    customer_group: "مجموعة العملاء *",
    pricing_group_label: "مجموعة التسعيرة",
    customer_name_label: "اسم العميل *",
    phone: "هاتف",
    email_address: "عنوان البريد الإلكتروني",
    commercial_register: "السجل التجاري",
    opening_balance: "رصيد افتتاحي *( المديونية بالسالب)",
    credit_limit: "الحد الائتماني *",
    stop_sale_if_overdue: "ايقاف البيع في حالة وجود مبالغ مستحقة",
    add_customer_button: "اضافة عميل",
    suppliers: "الموردين",
    suppliers_list: "قائمة الموردين",
    add_supplier: "إضافة مورد",
    tax_number: "الرقم الضريبي",
    commercial_registration: "السجل التجاري",
    amount_due_to_supplier: "المبلغ المستحق للمورد",
    please_enter_supplier_name: "الرجاء إدخال اسم المورد",
    supplier_added_successfully: "تم إضافة المورد بنجاح",
    supplier_updated_successfully: "تم تحديث بيانات المورد بنجاح",
    please_enter_info_below: "برجاء ادخال المعلومات أدناه. تسميات الحقول التي تحمل علامة * هي حقول اجبارية .",
    supplier_name: "اسم المورد",
    edit_supplier: "تعديل مورد",
    banks: "البنوك",
    banks_list: "قائمة البنوك",
    add_bank: "إضافة بنك",
    bank_code: "كود البنك",
    bank_name: "اسم البنك",
    bank_opening_balance: "الرصيد الافتتاحي",
    current_balance: "الرصيد الحالي",
    edit_bank: "تعديل بنك",
    please_enter_bank_info: "برجاء ادخال المعلومات أدناه. تسميات الحقول التي تحمل علامة * هي حقول اجبارية .",
    bank_updated_successfully: "تم تعديل البنك بنجاح",
    bank_deleted_successfully: "تم حذف البنك بنجاح",
    confirm_delete_bank: "هل أنت متأكد من حذف هذا البنك؟",
    default_bank: "البنك الافتراضي",
    external_transfers: "تحويلات بنكية خارجية",
    external_transfers_list: "تحويلات بنكية خارجية",
    internal_transfers_list: "تحويلات بنكية داخلية",
    add_external_transfer: "إضافة تحويل بنكي خارجي",
    add_internal_transfer: "إضافة تحويل بنكي داخلي",
    transfer_type: "نوع التحويل",
    transfer_from: "تحويل من",
    transfer_to: "تحويل إلى",
    fund_balance: "رصيد الصندوق",
    select_bank: "البنك",
    select_transfer_type: "اختر نوع التحويل",
    transfer_from_fund: "تحويل من صندوق",
    transfer_to_fund: "تحويل إلى صندوق",
    please_enter_transfer_info: "برجاء ادخال المعلومات أدناه. تسميات الحقول التي تحمل علامة * هي حقول اجبارية .",
    transfer_added_successfully: "تم إضافة التحويل بنجاح",
    confirm_delete_transfer: "هل أنت متأكد من حذف هذا التحويل؟",
    internal_transfers: "تحويلات بنكية داخلية",
    bonds: "السندات",
    receipt_bonds: "سندات قبض نقدية",
    add_receipt_bond: "إضافة سند قبض نقدية",
    add_receipt_bond_btn: "إضافة سند قبض نقدي",
    payment_bonds: "سندات صرف نقدية",
    add_payment_bond: "إضافة سند صرف نقدية",
    add_payment_bond_btn: "إضافة سند صرف",
    deposit_bonds: "سندات ايداع نقدية في البنك",
    add_deposit_bond: "إضافة سند ايداع نقدية في البنك",
    add_deposit_bond_btn: "إضافة سند إيداع",
    withdrawal_bonds: "سحوبات النقدية من البنك",
    add_withdrawal_bond: "إضافة سند سحب نقدية من البنك",
    add_withdrawal_bond_btn: "إضافة سند سحب",
    beneficiary: "المستفيد",
    withdrawn_amount: "المبلغ المسحوب",
    bank: "البنك",
    save: "حفظ",
    update_bond: "تحديث السند",
    bond_added_successfully: "تم إضافة السند بنجاح",
    bond_updated_successfully: "تم تحديث السند بنجاح",
    bond_deleted_successfully: "تم حذف السند بنجاح",
    confirm_delete_bond: "هل أنت متأكد من حذف هذا السند؟",
    receipt_bond_title: "إضافة سند قبض نقدية",
    payment_bond_title: "إضافة سند صرف نقدية",
    deposit_bond_title: "إضافة سند ايداع نقدية في البنك",
    withdrawal_bond_title: "إضافة سند سحب نقدية من البنك",
    edit_receipt_bond_title: "تعديل سند قبض نقدية",
    edit_payment_bond_title: "تعديل سند صرف نقدية",
    edit_deposit_bond_title: "تعديل سند ايداع نقدية في البنك",
    edit_withdrawal_bond_title: "تعديل سند سحب نقدية من البنك",
    no_bonds_found: "لا توجد بيانات في الجدول",
    bonds_table_desc: "الرجاء استخدام الجدول أدناه للتنقل أو تصفية النتائج.",
    settings: "الإعدادات",
    system_settings: "إعدادات النظام",
    site_settings: "إعدادات الموقع",
    items_settings: "الأصناف",
    sales_settings: "المبيعات",
    prefixes_settings: "بادئة",
    money_formatting: "تنسيق المال والأعداد",
    barcode_scale: "ميزان الباركود",
    email_settings: "البريد الإلكتروني",
    earned_points: "اجمالي النقاط المكتسبة",
    sales_fees: "رسوم البيع",
    report_print_settings: "إعدادات التقارير",
    sales_print_settings: "إعدادات طباعة المبيعات",
    company_name: "اسم الشركة",
    accounting_method: "طريقة المحاسبة",
    default_email: "البريد الالكتروني الافتراضي",
    default_customer_group: "المجموعة العملاء الافتراضية",
    general_price_group: "مجموعة الأسعار العامة",
    rtl_support: "دعم RTL",
    rows_per_page: "الصفوف لكل صفحة",
    timezone: "المنطقة الزمنية",
    default_branch: "الفرع الافتراضي",
    default_cashier: "الكاشير الافتراضي",
    pdf_library: "PDF Library",
    warranty_alert_days: "عدد أيام تنبيه الصلاحية",
    show_actual_balance: "إظهار الرصيد الفعلي في قائمة العملاء",
    show_cost_message: "إظهار رسالة التكلفة أكبر من سعر البيع",
    show_item_code_sales: "إظهار كود الصنف في المبيعات",
    show_item_code_quotes: "إظهار كود الصنف في عروض الأسعار",
    show_item_code_purchases: "إظهار كود الصنف في المشتريات",
    save_settings: "حفظ التعديلات",
    payment_companies: "شركات الدفع",
    add_payment_company: "اضافة شركة مدفوعات",
    edit_payment_company: "تعديل شركة مدفوعات",
    company_code: "كود الشركة المميز",
    company_name_label: "اسم",
    payment_methods: "طرق الدفع",
    add_payment_method: "إضافة طريقة دفع",
    edit_payment_method: "تعديل طريقة دفع",
    payment_method_code: "الكود",
    payment_method_name: "اسم",
    payment_method_status: "الحالة",
    payment_method_image: "صورة",
    available: "متاح",
    unavailable: "غير متاح",
    pos_settings: "إعدادات نقاط البيع",
    pos_config: "تكوين نقاط البيع",
    pos_printing: "طباعة POS",
    custom_fields_receipt: "الحقول المخصصة على ايصال الطابعة",
    receipt_settings: "إعدادات الإيصال",
    shortcuts: "الاختصارات",
    display_items: "عرض الاصناف",
    default_category: "الفئة الافتراضية",
    default_customer: "العميل الافتراضي",
    display_time: "عرض الوقت",
    on_screen_keyboard: "لوحة المفاتيح على الشاشة",
    instructions_tool: "أداة الإرشادات",
    rounding: "التقريب",
    item_order: "ترتيب العنصر",
    after_sale_page: "بعد صفحة المبيعات",
    print_customer_details: "طباعة بيانات العميل على الإيصال",
    display_tax_details: "عرض تفاصيل الضريبة",
    enable_bill_suspension: "إمكانية تعليق الفاتورة",
    cancel_item_from_bill: "الغاء صنف من الفاتورة",
    enable_bill_cancellation: "إمكانية الغاء الفاتورة",
    operation_password: "كلمة المرور للعمليات",
    enable_order_number: "تفعيل رقم الطلب",
    enable_display_screen: "تفعيل شاشة العرض",
    enable_alert_sound: "تفعيل صوت التنبيه",
    enable_additions: "تفعيل الاضافات",
    enable_short_sales_report: "تفعيل تقرير مبيعات مختصر",
    enable_daily_sales_report: "تفعيل تقرير مبيعات اليوم",
    enable_reservations: "تفعيل الحجوزات",
    printer: "طباعة",
    custom_field_1_value: "حقل مخصص 1 القيمة",
    print_address: "طباعة العنوان",
    print_extra_id: "طباعة المعرف الإضافي",
    print_phone_number: "طباعة رقم الهاتف",
    print_tax_number: "طباعة الرقم الضريبي",
    print_reference_number: "طباعة الرقم المرجعي",
    print_cashier: "طباعة الكاشير",
    print_employee: "طباعة الموظف",
    print_barcode_receipt: "طباعة الباركود",
    print_discount: "عرض الخصم",
    focus_search: "المؤشر مكان البحث عن الصنف",
    cancel_sale: "إلغاء بيع",
    suspend_sale: "تعليق بيع",
    last_invoice: "اخر فاتورة",
    finish_sale: "إنهاء المبيع",
    today_sales: "مبيعات اليوم",
    open_suspended_sales: "المبيعات المعلقة المفتوحة",
    close_shift: "اغلاق الوردية",
    pos_settings_update_msg: "يرجى تحديث المعلومات الواردة أدناه. تسميات الحقول التي تحمل علامة * هي حقول اجبارية .",
    delivery_companies: "شركات التوصيل",
    delegates_and_employees: "المندوبين والموظفين",
    add_delegate_or_employee: "إضافة مندوب أو موظف",
    edit_delegate_or_employee: "تعديل مندوب أو موظف",
    add_table: "إضافة طاولة",
    edit_table: "تعديل طاولة",
    additions: "الإضافات",
    add_addition: "إضافة اضافات جديدة",
    edit_addition: "تعديل إضافة",
    warehouses: "المستودعات",
    add_warehouse: "إضافة مستودع",
    edit_warehouse: "تعديل مستودع",
    select_branch: "اختر الفرع",
    show_touch_screen: "إظهار شاشة اللمس",
    enable_tables: "تفعيل الطاولات",
    print_prep_slip: "طباعة بون التجهيز",
    enable_marketers: "تفعيل المسوقين",
    enable_glasses: "تفعيل النظارات",
    print_sizes_on_invoice: "طباعة المقاسات في الفاتورة",
    map: "خريطة",
    code: "الكود",
    region: "المنطقة",
    add_region: "إضافة منطقة",
    add_delivery_company: "إضافة شركة توصيل",
    edit_delivery_company: "تعديل شركة توصيل",
    promotions: "العروض الترويجية",
    special_promotions: "عروض ترويجية مخصصة",
    general_promotions: "عروض ترويجية عامة",
    add_special_promotion: "إضافة عروض ترويجية خاصة",
    edit_special_promotion: "تعديل عرض ترويجي خاص",
    add_general_promotion: "إضافة عروض ترويجية عامة",
    save_changes: "حفظ التعديلات",
    promotion_name: "اسم العرض",
    basic_item: "الصنف الاساسي",
    basic_item_qty: "كمية الصنف الاساسي",
    free_item: "الصنف المجاني",
    free_item_qty: "كمية الصنف المجاني",
    promotion_policy: "سياسة العرض",
    promotion_details: "التفاصيل",
    promotion_discount: "خصم",
    promotion_branch: "الفرع",
    promotion_start_date: "تاريخ البداية",
    promotion_end_date: "تاريخ النهاية",
    promotion_actions: "الإجراءات",
    no_promotions_found: "لا توجد بيانات في الجدول",
    promotion_save: "اضافة عرض ترويجي",
    promotion_form_title: "برجاء ادخال المعلومات أدناه. تسميات الحقول التي تحمل علامة * هي حقول اجبارية .",
    promotion_policy_option1: "تطبيق على أول كمية من الصنف الأساسي",
    promotion_policy_option2: "تطبيق على جميع كميات الصنف الأساسي",
    change_logo: "تغيير اللوجو",
    currencies: "العملات",
    add_currency: "إضافة عملة",
    edit_currency: "تعديل عملة",
    currency_code: "رمز العملة",
    currency_name: "اسم العملة",
    exchange_rate: "سعر الصرف",
    symbol: "الرمز",
    auto_update: "معدل التحديث التلقائي",
    currencies_table_desc: "الرجاء استخدام الجدول أدناه للتنقل أو تصفية النتائج.",
    customer_groups: "مجموعات العملاء",
    add_customer_group: "إضافة مجموعة العملاء",
    edit_customer_group: "تعديل مجموعة العملاء",
    update_customer_group: "تحديث مجموعة العملاء",
    group_percentage_no_sign: "النسبة المئوية لمجموعة (بدون علامة%)",
    sell_at_cost: "البيع بسعر التكلفة",
    group_name_placeholder: "ادخل اسم المجموعة",
    customer_groups_table_desc: "الرجاء استخدام الجدول أدناه للتنقل أو تصفية النتائج.",
    percentage: "نسبة مئوية",
    pricing_groups: "مجموعات التسعيرة",
    add_pricing_group: "إضافة مجموعة تسعيرة",
    edit_pricing_group: "تعديل مجموعة تسعيرة",
    update_pricing_group: "تحديث مجموعة تسعيرة",
    pricing_group_info: "برجاء ادخال المعلومات أدناه. تسميات الحقول التي تحمل علامة * هي حقول اجبارية .",
    search_pricing_groups: "بحث في مجموعات التسعيرة",
    enter_group_name: "ادخل اسم المجموعة",
    basic_categories: "التصنيفات الأساسية",
    expense_categories: "تصنيفات المصروفات",
    brands: "الماركات",
    variants: "المتغيرات",
    tax_rates: "أسعار الضريبة",
    regions: "المناطق",
    delegates: "المندوبين و الموظفين",
    tables: "الطاولات",
    branches: "الفروع",
    production_machines: "ماكينات الانتاج",
    group_permissions: "ضوابط وصلاحيات المجموعة",
    site_logins: "تسجيلات دخول الموقع",
    reports: "التقارير",
    add_group: "إضافة مجموعة",
    edit_group: "تعديل مجموعة مستخدمي",
    delete_group_confirm: "هل أنت متأكد من حذف هذه المجموعة؟",
    permissions: "الصلاحيات",
    group_name_label: "اسم المجموعة",
    group_description_label: "وصف المجموعة",
    module: "الموديول",
    view_permission: "عرض",
    add_permission: "إضافة",
    edit_permission: "تعديل",
    delete_permission: "حذف",
    save_permissions: "حفظ الصلاحيات",
    notifications: "الإشعارات",
    no_notifications: "لا يوجد إشعارات جديدة",
    language: "اللغة",
    arabic: "العربية",
    english: "English",
    profile: "الملف الشخصي",
    logout: "تسجيل الخروج",
    search: "بحث...",
    welcome: "أهلاً بك",
    admin: "مدير النظام",
    view_all: "عرض الكل",
    new_order: "طلب جديد",
    order_desc: "تم استلام طلب جديد #1234",
    system_update: "تحديث النظام",
    update_desc: "تم تحديث النظام بنجاح",
    low_stock: "تنبيه مخزون",
    stock_desc: "المنتج X وصل للحد الأدنى",
    // Dashboard
    loading_data: "جاري تحميل البيانات...",
    renewal_request_sent: "تم الاشتراك بنجاح",
    welcome_admin: "أهلاً بك، مدير النظام",
    total_operations_date: "إجمالي العمليات لتاريخ",
    renew_subscription_days: "تجديد الإشتراك - الأيام المتبقية: 937 يوم",
    total_sales: "إجمالي المبيعات",
    currency_sar: "ر.س",
    total_purchases: "إجمالي المشتريات",
    net_profit: "صافي الأرباح",
    total_receivables: "إجمالي المستحقات",
    chart_overview: "نظرة عامة على الرسم البياني",
    last_6_months: "آخر 6 أشهر",
    last_year: "آخر سنة",
    recent_transactions: "أحدث العمليات",
    // Login
    login: "تسجيل الدخول",
    welcome_login_message: "مرحبا بك، سجل الدخول للمتابعة",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    remember_me: "تذكرني",
    forgot_password: "نسيت كلمة المرور؟",
    login_button: "دخول",
    login_footer_text: "ما تحتاجه لإدارة اعمالك بكل سهولة فى مكان واحد",
    copyright_text: "takamul V1.10 جميع الحقوق محفوظة @2026",
    // Recent Transactions
    stock_transfers: "تحويل المخزون",
    id: "#",
    date: "التاريخ",
    invoice_no: "رقم الفاتورة",
    ref_no: "الرقم المرجعي",
    customer: "العميل",
    status: "الحالة",
    total: "المجموع",
    general_person: "شخص عام",
    completed: "مكتملة",
    no_data_display: "لا توجد بيانات للعرض حالياً في هذا القسم",
    // Forgot Password
    password_recovery: "استعادة كلمة المرور",
    password_recovery_desc: "الرجاء إدخال البريد الإلكتروني أو اسم المستخدم المرتبط بحسابك لاستلام رابط إعادة تعيين كلمة المرور.",
    email_username: "البريد الإلكتروني / اسم المستخدم",
    send_recovery_link: "إرسال رابط الاستعادة",
    sent_successfully: "تم الإرسال بنجاح",
    recovery_email_sent_desc: "إذا كان هذا الحساب موجوداً، فقد تم إرسال تعليمات استعادة كلمة المرور إلى بريدك الإلكتروني.",
    back_to_login: "العودة لتسجيل الدخول",
    // Products List
    home: "البداية",
    products_all_branches: "الأصناف (جميع الفروع)",
    products_table_desc: "الرجاء استخدام الجدول أدناه للتنقل أو تصفية النتائج.",
    update_prices: "تحديث الأسعار",
    delete: "حذف",
    confirm_delete_count: "هل أنت متأكد من حذف",
    items_question: "عنصر؟",
    confirm_delete_product: "هل أنت متأكد من حذف هذا الصنف؟",
    update_prices_title: "تحديث الأسعار",
    update_prices_desc: "يرجى رفع ملف Excel يحتوي على الأسعار الجديدة",
    choose_file: "اختر ملف",
    show: "اظهر",
    search_placeholder: "اكتب ما تريد ان تبحث عنه",
    image: "صورة",
    product_code: "كود الصنف",
    name: "اسم",
    brand: "الماركة",
    agent: "الوكيل",
    main_categories: "التصنيفات الرئيسية",
    cost: "التكلفة",
    selling_price: "سعر البيع",
    quantity: "كمية",
    unit: "وحدة",
    stock_alerts: "تنبيهات بكميات المخزون",
    actions: "الإجراءات",
    duplicate_group: "تكرار التصنيف",
    delete_group: "حذف التصنيف",
    duplicate_product: "تكرار الصنف",
    edit_product: "تعديل الصنف",
    print_barcode_labels: "طباعة باركود - الملصقات",
    branch_prices: "الأسعار في الفروع",
    branch_prices_soon: "ميزة الأسعار في الفروع ستتوفر قريباً",
    product_available_in_branch: "الصنف متاح في هذا الفرع",
    internal_units_count: "عدد الوحدات الداخلية",
    wholesale_price: "سعر الجملة",
    edit_product_btn: "تعديل الصنف",
    view_quote: "عرض سعر",
    edit_quote_action: "تعديل عرض السعر",
    create_sales_invoice: "إنشاء فاتورة مبيعات",
    create_purchase_invoice: "إنشاء فاتورة مشتريات",
    download_pdf_quote: "تحميل بصيغة PDF",
    send_email_quote: "ارسال عرض السعر بالبريد الالكتروني",
    delete_quote_action: "حذف عرض السعر",
    quote_no: "رقم العرض",
    quote_no_title: "رقم عرض السعر",
    description: "وصف",
    item_no: "م",
    data_entry: "مدخل البيانات",
    updated_by: "تحديث قام به",
    updated_at: "تم التحديث في",
    sold_qty: "الكمية المباعة",
    total_no_vat: "الاجمالي بدون ضريبة",
    unit_price_no_vat: "سعر الوحدة بدون ضريبة",
    unit_price_with_vat: "سعر الوحدة بالضريبة",
    product_total: "اجمالي الصنف",
    attach_documents: "إرفاق المستندات",
    complete_process: "اتمام العملية",
    all_branches: "جميع الفروع",
    shipping: "الشحن",
    view: "عرض",
    pdf_btn: "PDF",
    email_btn: "البريد الإلكتروني",
    edit_btn: "تعديل",
    delete_btn: "حذف",
    edit: "تعديل",
    select_customer: "اختر عميل",
    delete_product: "حذف الصنف",
    showing_records: "عرض",
    to: "إلى",
    of: "من",
    records: "سجلات",
    previous: "سابق",
    next: "التالي",
    copy_suffix: "(نسخة)",
    // Add Product
    add_product_title: "إضافة الصنف",
    add_product_desc: "برجاء ادخال المعلومات أدناه. تسميات الحقول التي تحمل علامة * هي حقول اجبارية .",
    product_type: "نوع الصنف *",
    general: "عام",
    service: "خدمي",
    product_name: "اسم الصنف *",
    product_name_second_lang: "اسم الصنف باللغة الثانية",
    product_name_sec_lang: "اسم الصنف باللغة الثانية",
    product_name_third_lang: "اسم الصنف باللغة الثالثة",
    product_code_required: "كود الصنف *",
    generate_code: "توليد كود",
    barcode_reader_hint: "يمكن إستخدام قاريء الباركود أيضاً",
    alt_code: "كود بديل",
    select_brand: "اختر الماركة",
    product_cost: "تكلفة الصنف *",
    product_price: "سعر الصنف *",
    max_order_qty: "أقصى كمية للطلب *",
    reorder_point: "حد الطلب",
    has_variants_label: "هذا الصنف لديها بدائل متعددة مثلا مقاسات متعددة و / أو الألوان",
    main_categories_required: "التصنيفات الرئيسية *",
    select_main_categories: "اختر التصنيفات الرئيسية",
    sub_category: "التصنيف الفرعي",
    select_category_load: "الرجاء تحديد الفئة للتحميل",
    product_unit: "وحدة الصنف *",
    select_unit: "اختر وحدة",
    default_sale_unit: "وحدة البيع الإفتراضية",
    default_purchase_unit: "وحدة الشراء الإفتراضية",
    additional_units: "وحدات اضافية",
    list_price_branch_order_limit: "مبلغ الليستة وحد الطلب للفروع",
    branch_name: "اسم الفرع",
    list_amount: "مبلغ اللسته",
    stock_alerts_header: "تنبيهات بكميات المخزون",
    accuracy_solutions_company: "شركة دقة الحلول",
    product_availability_branches: "إتاحية الصنف في الفروع",
    status_header: "الحالة",
    yes: "نعم",
    no: "لا",
    product_image: "صورة الصنف",
    browse: "استعراض ...",
    product_gallery: "كتالوج صور الصنف",
    stock_item: "صنف مخزون",
    hide_pos: "اخفاء في شاشة نقاط البيع",
    featured_product: "متميز (ضعه في رئسية المتجر إن كان مفعل)",
    new_arrival: "وصل حديثا",
    hide_store: "اخفاء في شاشة المتجر",
    product_details: "تفاصيل الصنف",
    // Import Products
    import_products_csv: "إضافة الأصناف من قبل CSV",
    download_sample_file: "تحميل ملف نموذج",
    csv_instruction_1: "ينبغي أن يظل السطر الأول في ملف CSV الذي يتم تحميله كما هو. يرجى عدم تغيير ترتيب الأعمدة.",
    csv_instruction_2: "ترتيب الأعمدة الصحيح...",
    csv_instruction_3: "يجب تحميل الصور في المجلد assets/uploads/ folder and thumbnails بنفس الاسم المذكور بملف CSV assets/uploads/thumbs/",
    csv_instruction_4: "سيقوم النظام بفحص اذا كان الكود خاص بأي من الأصناف المخزنة . غير ذلك سيتم اضافة الصنف كصنف جديد",
    upload_file: "تحميل الملف *",
    import: "استيراد",
    // Print Barcode
    print_barcode_labels_title: "طباعة باركود - الملصقات",
    sales_all_branches: "المبيعات (جميع الفروع)",
    sales_table_desc: "البيانات الظاهرة في آخر 30 يوم . برجاء استخدام النموذج لإظهار مزيد من النتائج",
    grand_total: "المجموع الكلي",
    remaining_amount: "المبلغ المتبقي",
    payment_type: "نوع الدفع",
    returned: "رجيع",
    returned_status: "مرتجع",
    partial: "جزئي",
    mada: "مدى",
    view_invoice: "عرض الفاتورة",
    edit_sale: "تعديل البيع",
    return_sale: "إرجاع البيع",
    delete_sale: "حذف البيع",
    total_records: "إجمالي السجلات",
    invoice_details: "تفاصيل فاتورة المبيعات",
    duplicate_sale: "تكرار فاتورة المبيعات",
    view_payments: "عرض المدفوعات",
    add_payment: "إضافة الدفع",
    store_bond: "سند مخزني",
    claim_bond: "سند مطالبة",
    add_delivery: "إضافة تسليم",
    download_pdf: "تحميل بصيغة PDF",
    download_excel: "تحميل كملف إكسل",
    download_csv: "تحميل بصيغة CSV",
    send_email: "ارسال الفاتورة بالبريد الالكتروني",
    send_whatsapp: "إرسال الفاتورة عبر الواتس",
    release_bond: "سند فسخ",
    edit_delegate: "تعديل المندوب / الموظف",
    gift_cards_list: "قائمة كروت الهدايا",
    add_gift_card: "إضافة بطاقة هدية",
    delete_gift_cards: "حذف كروت الهدايا",
    card_no: "رقم البطاقة",
    value: "القيمة",
    notes: "ملاحظات",
    expiry_date: "تاريخ الإنتهاء",
    walk_in_customer: "عميل افتراضي",
    use_employee_points_program: "استخدام برنامج نقاط الموظف",
    gift_cards_table_desc: "الرجاء استخدام الجدول أدناه للتنقل أو تصفية النتائج.",
    no_data_in_table: "لا توجد بيانات في الجدول",
    payment_view_title: "عرض المدفوعات (بيع المرجع: {ref})",
    store_bond_title: "سند مخزني",
    claim_letter_title: "نموذج خطاب مطالبة مالية",
    delivery_title: "إضافة تسليم",
    delivery_status: "الحالة *",
    delivery_ref: "الرقم المرجعي للتسليم",
    sale_ref: "الرقم المرجعي للبيع *",
    address: "العنوان *",
    attachments: "ملحقات",
    note: "مذكرة",
    add_delivery_btn: "إضافة تسليم",
    edit_payment: "تعديل الدفع",
    edit_payment_desc: "برجاء ادخال المعلومات أدناه. تسميات الحقول التي تحمل علامة * هي حقول اجبارية .",
    payment_ref: "الرقم المرجعي",
    receipt_bond: "سند قبض",
    received_from: "استلمنا من السيد",
    amount_of: "مبلغ وقدره",
    for_payment: "وذلك مقابل",
    seal_signature: "الختم أو التوقيع",
    receiver: "المستلم",
    email_sent_success: "تم ارسال الايميل بنجاح",
    print_barcode_desc: "يمكنك زيارة التصنيفات الأساسية, التصنيفات الفرعية, مشتريات و تحويل المخزون لإضافة الأصناف لقائمة الطباعة",
    add_product_label: "إضافة الصنف",
    activity_name: "اسم النشاط",
    expiry: "انتهاء",
    production: "انتاج",
    product_name_code: "اسم الصنف (كود الصنف)",
    no_products_added: "لا توجد أصناف مضافة",
    print_method: "طريقة الطباعة *",
    continuous_print: "طباعة مستمرة(طابعة باركود)",
    a4_paper: "ورقة A4",
    width: "العرض",
    mm: "مللي",
    height: "الإرتفاع",
    barcode_height: "ارتفاع أعمدة الباركود",
    px: "px",
    barcode_orientation: "اتجاه أعمدة الباركود",
    vertical: "عمودي",
    horizontal: "أفقي",
    check_promo_price: "فحص سعر الترويج",
    print: "طباعة",
    tax_inclusive: "شامل ضريبة",
    font_formatting: "تنسيق الخطوط",
    format_product_name: "تنسيق اسم الصنف",
    format_activity_name: "تنسيق اسم النشاط",
    format_dates: "تنسيق تاريخ الانتاج والإنتهاء",
    format_price: "تنسيق السعر",
    font_size: "حجم الخط",
    spacing: "التباعد",
    font_color: "لون الخط",
    bg_color: "لون الخلفية",
    update: "تحديث",
    light_mode: "الوضع الفاتح",
    dark_mode: "الوضع الداكن",
    red_theme: "الثيم الأحمر",
    blue_theme: "الثيم الأزرق",
    yellow_theme: "الثيم الأصفر",
    high_contrast: "تباين عالي",
    filter_results: "تصفية النتائج",
    from_date: "من تاريخ",
    to_date: "الى تاريخ",
    export_to_excel: "تصدير إلى ملف Excel",
    export_to_pdf: "تصدير إلى ملف pdf",
    delete_selected_items: "حذف الأصناف المحددة",
    edit_delivery: "تعديل تسليم",
    delivery_ref_no: "الرقم المرجعي للتسليم",
    sale_ref_no: "الرقم المرجعي للبيع",
    delivered_by: "تمت عمليه التوصيل من قبل",
    received_by: "تم الاستلام من قبل",
    shelf: "رف",
    in_progress: "جاري العمل عليه",
    delivered: "تم التوصيل",
    delivery_failed: "فشل التوصيل",
    financial_claim_letter: "نموذج خطاب مطالبة مالية",
    sender: "المرسل",
    recipient: "المستلم",
    subject: "الموضوع",
    financial_claim_subject: "مطالبة مالية بسداد مبلغ معين",
    municipality_license: "رخصة البلدية",
    sales_invoice: "فاتورة مبيعات",
    product_description: "بيان الصنف",
    price: "السعر",
    customer_details: "بيانات العميل",
    customer_no: "رقم العميل",
    customer_name: "اسم العميل",
    customer_tax_no: "الرقم الضريبي للعميل",
    mobile_no: "رقم الجوال",
    city: "المدينة",
    district: "الحي",
    street_name: "اسم الشارع",
    tax_no: "الرقم الضريبي",
    unit_price: "سعر الوحدة",
    pay: "دفع",
    delivery: "التسليم",
    view_payments_ref: "عرض المدفوعات (بيع المرجع: {ref})",
    invoice_date: "تاريخ اصدار الفاتورة",
    invoice_type: "نوع الفاتورة",
    thank_you: "شكراً لزيارتكم",
    see_you_again: "ننتظركم مرة أخرى",
    return_policy: "للإرجاع والاستبدال خلال 48 ساعة",
    bring_invoice: "يجب احضار الفاتورة",
    dear: "السادة",
    greetings: "تحية طيبة",
    claim_letter_body_1: "نود تذكيركم بأن الفاتورة رقم {invoiceNo} الصادرة بتاريخ {date}م والمتعلقة بقيمة {amount} ريال ({amountText}) كان من المفترض سدادها بحلول __________ وحتى تاريخ هذا الخطاب لم يتم استلام مبلغ الفاتورة.",
    claim_letter_body_2: "لذلك نرجو منكم تسديد المبلغ المستحق خلال 7 أيام من تاريخه، وذلك عبر الحساب البنكي المرفق في الفاتورة.",
    claim_letter_body_3: "في حال عدم السداد خلال المهلة المحددة سنضطر آسفين لاتخاذ الإجراءات القانونية اللازمة لتحصيل المستحقات.",
    best_regards: "وتفضلو بقبول فائق الاحترام.",
    company_stamp: "ختم الشركة",
    sales_report_by_category: "تقرير المبيعات حسب التصنيفات",
    customize_report_below: "يرجى تخصيص التقرير أدناه",
    total_sales_report: "مجموع المبيعات",
    profit: "ربح",
    show_records: "اظهار",
    category_code_placeholder: "[كود الصنف]",
    category_name_placeholder: "[اسم الصنف]",
    treasuries: "الخزائن",
    treasurys: "الخزائن",
    treasurys_list: "قائمة الخزائن",
    treasuries_page_title: "قائمة الخزائن",
    treasury_code: "كود الخزينة",
    treasury_name: "اسم الخزينة",
    treasury_opening_balance: "الرصيد الافتتاحي",
    treasury_search_placeholder: "ابحث بالكود أو اسم الخزينة...",
    add_treasury_btn: "إضافة خزينة",
    deleted_successfully: "تم الحذف بنجاح",
    something_went_wrong: "حدث خطأ ما",
    no_data: "لا توجد بيانات",
  
  },
  en: {
    confirm_delete_title: "Confirm Delete",
    confirm_delete_desc: "Are you sure you want to delete this item?",
    confirm_delete_btn: "Delete",
    cancel: "Cancel",
    dashboard: "Dashboard",
    products: "Products",
    products_list: "Products List",
    add_product: "Add Product",
    import_products: "Import Products",
    print_barcode: "Print Barcode",
    print_barcode_stickers: "Print Barcode",
    quantity_adjustments: "Quantity Adjustments",

    groups: "Categories",
    add_new_group: "Add New Category",
    units: "Units",
    group_code: "Category Code",
    group_name: "Category Name",
    group_name_secondary_lang: "Category Name in Second Language",
    group_image: "Category Image",
    add_new_unit: "Add New Unit",
    unit_code: "Unit Code",
    unit_name: "Unit Name",
    sales: "Sales",
    all_sales: "All Sales",
    sales_a4_quick: "A4 Sales",
    a4_sales_title: "Add A4 Sales",
    add_sale_operation: "Add Sale Operation",
    cashier: "Cashier",
    branch: "Branch",
    customer_label: "Customer",
    delegate_employee: "Delegate / Employee",
    po_number: "P.O. Number",
    project_name: "Project Name",
    please_add_items: "Please add items",
    update_options_before_adding: "Please update these options before adding any product",
    product_code_name: "Product (Code - Name)",
    unit_price_no_tax: "Unit Price (No Tax)",
    unit_price_with_tax: "Unit Price (With Tax)",
    sold_quantity: "Sold Quantity",
    total_no_tax: "Total (No Tax)",
    total_product_sr: "Total Product (SR)",
    discount: "Discount",
    sale_status: "Sale Status *",
    due_date: "Due Date",
    paid_amount: "Paid Amount",
    payment_by: "Payment By *",
    add_more_payments: "Add More Payments",
    sale_notes: "Sale Notes",
    complete_operation: "Complete Operation",
    deposits_list: "Deposits List",
    add_deposit: "Add Deposit",
    discounts_list: "Discounts List",
    add_discount: "Add Discount",
    edit_customer: "Edit Customer",
    close: "Close",
    preview_invoice: "Preview Invoice",
    reset_form: "Reset",
    operation_completed_successfully: "Operation completed successfully!",
    operation_added_successfully: "Operation added successfully",
    preview_invoice_msg: "Preparing invoice preview...",
    network: "Network",
    cash: "Cash",
    bank_transfer: "Bank Transfer",
    pos_quick: "POS",
    invoices_a4: "A4 Invoices",
    invoices_pos: "POS Invoices",
    new_sale: "New Sale",
    add_tax_invoice: "Add Tax Invoice",
    add_simplified_tax_invoice: "Add Simplified Tax Invoice",
    add_sale_csv: "Add Sale from CSV",
    gift_cards: "Gift Cards",
    quotes: "Quotes",
    quotes_list: "Quotes List",
    add_quote: "Add Quote",
    purchases: "Purchases",
    purchases_list: "Purchases List",
    purchases_all_branches: "Purchases (All Branches)",
    supplier: "Supplier",
    purchase_status: "Purchase Status",
    paid: "Paid",
    balance: "Balance",
    payment_status: "Payment Status",
    purchase_invoice_type: "Purchase Invoice Type",
    all: "All",
    purchase_details: "Purchase Details",
    add_purchase: "Add Purchase",
    add_purchase_csv: "Add Purchase from CSV",
    expenses_list: "Expenses List",
    add_expense: "Add Expense",
    transfers: "Stock Transfers",
    transfers_list: "Transfers List",
    add_transfer: "Add Transfer",
    add_transfer_csv: "Add Transfer from CSV",
    users: "Users & Devices",
    users_list: "Users List",
    user_groups: "User Groups",
    add_user: "Add User",
    confirm_delete_user: "Are you sure you want to delete this user?",
    first_name: "First Name",
    last_name: "Last Name",
    gender: "Gender",
    male: "Male",
    female: "Female",
    company: "Company",
    username_email: "Username / Email",
    confirm_password: "Confirm Password",
    passwords_do_not_match: "Passwords do not match",
    active: "Active",
    inactive: "Inactive",
    group: "Group",
    default_payment_method: "Default Payment Method",
    default_payment_company: "Default Payment Company",
    default_invoice_type: "Default Invoice Type",
    notify_user_email: "Notify user via email",
    add_user_btn: "Add User",
    password_hint: "Password must contain an uppercase letter or symbol and a number",
    pos_devices: "Invoice Issuing Devices",
    add_device: "Add Device",
    additional_id: "Additional ID",
    confirm_delete_device: "Are you sure you want to delete this device?",
    customers: "Customers",
    customers_list: "Customers List",
    add_customer: "Add Customer",
    please_select_customer_type: "Please select customer type",
    not_registered_tax: "Not registered for tax",
    registered_tax: "Registered for tax",
    customer_group: "Customer Group *",
    pricing_group_label: "Pricing Group",
    customer_name_label: "Customer Name *",
    phone: "Phone",
    email_address: "Email Address",
    commercial_register: "Commercial Register",
    opening_balance: "Opening Balance * (Negative for debt)",
    credit_limit: "Credit Limit *",
    stop_sale_if_overdue: "Stop sale if there are overdue amounts",
    add_customer_button: "Add Customer",
    suppliers: "Suppliers",
    suppliers_list: "Suppliers List",
    add_supplier: "Add Supplier",
    tax_number: "Tax Number",
    commercial_registration: "Commercial Registration",
    amount_due_to_supplier: "Amount due to supplier",
    please_enter_supplier_name: "Please enter supplier name",
    supplier_added_successfully: "Supplier added successfully",
    supplier_updated_successfully: "Supplier updated successfully",
    please_enter_info_below: "Please enter the information below. Fields marked with * are mandatory.",
    supplier_name: "Supplier Name",
    edit_supplier: "Edit Supplier",
    banks: "Banks",
    banks_list: "Banks List",
    add_bank: "Add Bank",
    bank_code: "Bank Code",
    bank_name: "Bank Name",
    bank_opening_balance: "Opening Balance",
    current_balance: "Current Balance",
    edit_bank: "Edit Bank",
    please_enter_bank_info: "Please enter the information below. Fields marked with * are required.",
    bank_updated_successfully: "Bank updated successfully",
    bank_deleted_successfully: "Bank deleted successfully",
    confirm_delete_bank: "Are you sure you want to delete this bank?",
    default_bank: "Default Bank",
    external_transfers: "External Transfers",
    external_transfers_list: "External Bank Transfers",
    internal_transfers_list: "Internal Bank Transfers",
    add_external_transfer: "Add External Bank Transfer",
    add_internal_transfer: "Add Internal Bank Transfer",
    transfer_type: "Transfer Type",
    transfer_from: "Transfer From",
    transfer_to: "Transfer To",
    fund_balance: "Fund Balance",
    select_bank: "Bank",
    select_transfer_type: "Select Transfer Type",
    transfer_from_fund: "Transfer from fund",
    transfer_to_fund: "Transfer to fund",
    please_enter_transfer_info: "Please enter the information below. Fields marked with * are required.",
    transfer_added_successfully: "Transfer added successfully",
    confirm_delete_transfer: "Are you sure you want to delete this transfer?",
    internal_transfers: "Internal Transfers",
    bonds: "Bonds",
    receipt_bonds: "Cash Receipt Bonds",
    add_receipt_bond: "Add Cash Receipt Bond",
    add_receipt_bond_btn: "Add Cash Receipt Bond",
    payment_bonds: "Cash Payment Bonds",
    add_payment_bond: "Add Cash Payment Bond",
    add_payment_bond_btn: "Add Payment Bond",
    deposit_bonds: "Bank Deposit Bonds",
    add_deposit_bond: "Add Bank Deposit Bond",
    add_deposit_bond_btn: "Add Deposit Bond",
    withdrawal_bonds: "Bank Withdrawal Bonds",
    add_withdrawal_bond: "Add Bank Withdrawal Bond",
    add_withdrawal_bond_btn: "Add Withdrawal Bond",
    beneficiary: "Beneficiary",
    withdrawn_amount: "Withdrawn Amount",
    bank: "Bank",
    save: "Save",
    update_bond: "Update Bond",
    bond_added_successfully: "Bond added successfully",
    bond_updated_successfully: "Bond updated successfully",
    bond_deleted_successfully: "Bond deleted successfully",
    confirm_delete_bond: "Are you sure you want to delete this bond?",
    receipt_bond_title: "Add Cash Receipt Bond",
    payment_bond_title: "Add Cash Payment Bond",
    deposit_bond_title: "Add Bank Deposit Bond",
    withdrawal_bond_title: "Add Bank Withdrawal Bond",
    edit_receipt_bond_title: "Edit Cash Receipt Bond",
    edit_payment_bond_title: "Edit Cash Payment Bond",
    edit_deposit_bond_title: "Edit Bank Deposit Bond",
    edit_withdrawal_bond_title: "Edit Bank Withdrawal Bond",
    no_bonds_found: "No bonds found in the table",
    bonds_table_desc: "Please use the table below to navigate or filter results.",
    settings: "Settings",
    system_settings: "System Settings",
    site_settings: "Site Settings",
    items_settings: "Items",
    sales_settings: "Sales",
    prefixes_settings: "Prefixes",
    money_formatting: "Money & Numbers Formatting",
    barcode_scale: "Barcode Scale",
    email_settings: "Email",
    earned_points: "Earned Points",
    sales_fees: "Sales Fees",
    report_print_settings: "Report Print Settings",
    sales_print_settings: "Sales Print Settings",
    company_name: "Company Name",
    accounting_method: "Accounting Method",
    default_email: "Default Email",
    default_customer_group: "Default Customer Group",
    general_price_group: "General Price Group",
    rtl_support: "RTL Support",
    rows_per_page: "Rows per page",
    timezone: "Timezone",
    default_branch: "Default Branch",
    default_cashier: "Default Cashier",
    pdf_library: "PDF Library",
    warranty_alert_days: "Warranty Alert Days",
    show_actual_balance: "Show Actual Balance in Customer List",
    show_cost_message: "Show Cost Message if higher than sale price",
    show_item_code_sales: "Show Item Code in Sales",
    show_item_code_quotes: "Show Item Code in Quotes",
    show_item_code_purchases: "Show Item Code in Purchases",
    save_settings: "Save Settings",
    payment_companies: "Payment Companies",
    add_payment_company: "Add Payment Company",
    edit_payment_company: "Edit Payment Company",
    company_code: "Unique Company Code",
    company_name_label: "Name",
    payment_methods: "Payment Methods",
    add_payment_method: "Add Payment Method",
    edit_payment_method: "Edit Payment Method",
    payment_method_code: "Code",
    payment_method_name: "Name",
    payment_method_status: "Status",
    payment_method_image: "Image",
    available: "Available",
    unavailable: "Unavailable",
    pos_settings: "POS Settings",
    pos_config: "POS Configuration",
    pos_printing: "POS Printing",
    custom_fields_receipt: "Custom Fields on Receipt",
    receipt_settings: "Receipt Settings",
    shortcuts: "Shortcuts",
    display_items: "Display Items",
    default_category: "Default Category",
    default_customer: "Default Customer",
    display_time: "Display Time",
    on_screen_keyboard: "On-screen Keyboard",
    instructions_tool: "Instructions Tool",
    rounding: "Rounding",
    item_order: "Item Order",
    after_sale_page: "After Sale Page",
    print_customer_details: "Print Customer Details on Receipt",
    display_tax_details: "Display Tax Details",
    enable_bill_suspension: "Enable Bill Suspension",
    cancel_item_from_bill: "Cancel Item from Bill",
    enable_bill_cancellation: "Enable Bill Cancellation",
    operation_password: "Operation Password",
    enable_order_number: "Enable Order Number",
    enable_display_screen: "Enable Display Screen",
    enable_alert_sound: "Enable Alert Sound",
    enable_additions: "Enable Additions",
    enable_short_sales_report: "Enable Short Sales Report",
    enable_daily_sales_report: "Enable Daily Sales Report",
    enable_reservations: "Enable Reservations",
    printer: "Printer",
    custom_field_1_value: "Custom Field 1 Value",
    print_address: "Print Address",
    print_extra_id: "Print Extra ID",
    print_phone_number: "Print Phone Number",
    print_tax_number: "Print Tax Number",
    print_reference_number: "Print Reference Number",
    print_cashier: "Print Cashier",
    print_employee: "Print Employee",
    print_barcode_receipt: "Print Barcode",
    print_discount: "Display Discount",
    focus_search: "Focus Search Input",
    cancel_sale: "Cancel Sale",
    suspend_sale: "Suspend Sale",
    last_invoice: "Last Invoice",
    finish_sale: "Finish Sale",
    today_sales: "Today's Sales",
    open_suspended_sales: "Open Suspended Sales",
    close_shift: "Close Shift",
    pos_settings_update_msg: "Please update the information below. Field labels marked with * are required fields.",
    delivery_companies: "Delivery Companies",
    delegates_and_employees: "Delegates and Employees",
    add_delegate_or_employee: "Add Delegate or Employee",
    edit_delegate_or_employee: "Edit Delegate or Employee",
    add_table: "Add Table",
    edit_table: "Edit Table",
    additions: "Additions",
    add_addition: "Add New Addition",
    edit_addition: "Edit Addition",
    warehouses: "Warehouses",
    add_warehouse: "Add Warehouse",
    edit_warehouse: "Edit Warehouse",
    select_branch: "Select Branch",
    show_touch_screen: "Show Touch Screen",
    enable_tables: "Enable Tables",
    print_prep_slip: "Print Prep Slip",
    enable_marketers: "Enable Marketers",
    enable_glasses: "Enable Glasses",
    print_sizes_on_invoice: "Print Sizes on Invoice",
    map: "Map",
    code: "Code",
    region: "Region",
    add_region: "Add Region",
    add_delivery_company: "Add Delivery Company",
    edit_delivery_company: "Edit Delivery Company",
    promotions: "Promotions",
    special_promotions: "Special Promotions",
    general_promotions: "General Promotions",
    add_special_promotion: "Add Special Promotion",
    edit_special_promotion: "Edit Special Promotion",
    add_general_promotion: "Add General Promotion",
    save_changes: "Save Changes",
    promotion_name: "Promotion Name",
    basic_item: "Basic Item",
    basic_item_qty: "Basic Item Quantity",
    free_item: "Free Item",
    free_item_qty: "Free Item Quantity",
    promotion_policy: "Promotion Policy",
    promotion_details: "Promotion Details",
    promotion_discount: "Discount",
    promotion_branch: "Branch",
    promotion_start_date: "Start Date",
    promotion_end_date: "End Date",
    promotion_actions: "Actions",
    no_promotions_found: "No promotions found in table",
    promotion_save: "Add Promotion",
    promotion_form_title: "Please enter the information below. Field names marked with * are mandatory.",
    promotion_policy_option1: "Apply to first quantity of basic item",
    promotion_policy_option2: "Apply to all quantities of basic item",
    change_logo: "Change Logo",
    currencies: "Currencies",
    add_currency: "Add Currency",
    edit_currency: "Edit Currency",
    currency_code: "Currency Code",
    currency_name: "Currency Name",
    exchange_rate: "Exchange Rate",
    symbol: "Symbol",
    auto_update: "Auto Update",
    currencies_table_desc: "Please use the table below to navigate or filter results.",
    customer_groups: "Customer Groups",
    add_customer_group: "Add Customer Group",
    edit_customer_group: "Edit Customer Group",
    update_customer_group: "Update Customer Group",
    group_percentage_no_sign: "Group Percentage (without % sign)",
    sell_at_cost: "Sell at cost price",
    group_name_placeholder: "Enter group name",
    customer_groups_table_desc: "Please use the table below to navigate or filter results.",
    percentage: "Percentage",
    pricing_groups: "Pricing Groups",
    add_pricing_group: "Add Pricing Group",
    edit_pricing_group: "Edit Pricing Group",
    update_pricing_group: "Update Pricing Group",
    pricing_group_info: "Please enter the information below. Field labels marked with * are mandatory.",
    search_pricing_groups: "Search Pricing Groups",
    enter_group_name: "Enter group name",
    basic_categories: "Basic Categories",
    expense_categories: "Expense Categories",
    brands: "Brands",
    variants: "Variants",
    tax_rates: "Tax Rates",
    regions: "Regions",
    delegates: "Delegates & Employees",
    tables: "Tables",
    branches: "Branches",
    production_machines: "Production Machines",
    group_permissions: "Group Permissions",
    site_logins: "Site Logins",
    reports: "Reports",
    add_group: "Add Group",
    edit_group: "Edit User Group",
    delete_group_confirm: "Are you sure you want to delete this group?",
    permissions: "Permissions",
    group_name_label: "Group Name",
    group_description_label: "Group Description",
    module: "Module",
    view_permission: "View",
    add_permission: "Add",
    edit_permission: "Edit",
    delete_permission: "Delete",
    save_permissions: "Save Permissions",
    notifications: "Notifications",
    no_notifications: "No new notifications",
    language: "Language",
    arabic: "Arabic",
    english: "English",
    profile: "Profile",
    logout: "Logout",
    search: "Search...",
    welcome: "Welcome",
    admin: "Admin",
    view_all: "View All",
    new_order: "New Order",
    order_desc: "New order received #1234",
    system_update: "System Update",
    update_desc: "System updated successfully",
    low_stock: "Stock Alert",
    stock_desc: "Product X reached minimum stock",
    // Dashboard
    loading_data: "Loading data...",
    renewal_request_sent: "Subscription successful",
    welcome_admin: "Welcome, System Admin",
    total_operations_date: "Total operations for date",
    renew_subscription_days: "Renew Subscription - Days remaining: 937 days",
    total_sales: "Total Sales",
    currency_sar: "SAR",
    total_purchases: "Total Purchases",
    net_profit: "Net Profit",
    total_receivables: "Total Receivables",
    chart_overview: "Chart Overview",
    last_6_months: "Last 6 Months",
    last_year: "Last Year",
    recent_transactions: "Recent Transactions",
    // Login
    login: "Login",
    welcome_login_message: "Welcome, login to continue",
    email: "Email",
    password: "Password",
    remember_me: "Remember me",
    forgot_password: "Forgot password?",
    login_button: "Login",
    login_footer_text: "Everything you need to manage your business easily in one place",
    copyright_text: "takamul V1.10 All rights reserved @2026",
    // Recent Transactions
    stock_transfers: "Stock Transfers",
    id: "#",
    date: "Date",
    invoice_no: "Invoice No",
    ref_no: "Reference No",
    customer: "Customer",
    status: "Status",
    total: "Total",
    general_person: "General Person",
    completed: "Completed",
    no_data_display: "No data to display in this section currently",
    // Forgot Password
    password_recovery: "Password Recovery",
    password_recovery_desc: "Please enter your email or username associated with your account to receive a password reset link.",
    email_username: "Email / Username",
    send_recovery_link: "Send Recovery Link",
    sent_successfully: "Sent Successfully",
    recovery_email_sent_desc: "If this account exists, password recovery instructions have been sent to your email.",
    back_to_login: "Back to Login",
    // Products List
    home: "Home",
    products_all_branches: "Products (All Branches)",
    products_table_desc: "Please use the table below to navigate or filter results.",
    update_prices: "Update Prices",
    delete: "Delete",
    confirm_delete_count: "Are you sure you want to delete",
    items_question: "items?",
    confirm_delete_product: "Are you sure you want to delete this product?",
    update_prices_title: "Update Prices",
    update_prices_desc: "Please upload an Excel file containing the new prices",
    choose_file: "Choose File",
    show: "Show",
    search_placeholder: "Type what you want to search for",
    image: "Image",
    product_code: "Product Code",
    name: "Name",
    brand: "Brand",
    agent: "Agent",
    main_categories: "Main Categories",
    cost: "Cost",
    selling_price: "Selling Price",
    quantity: "Quantity",
    unit: "Unit",
    stock_alerts: "Stock Alerts",
    actions: "Actions",
    duplicate_group: "Duplicate Category",
    delete_group: "Delete Category",
    duplicate_product: "Duplicate Product",
    edit_product: "Edit Product",
    print_barcode_labels: "Print Barcode - Labels",
    branch_prices: "Branch Prices",
    branch_prices_soon: "Branch prices feature will be available soon",
    product_available_in_branch: "Product available in this branch",
    internal_units_count: "Internal Units Count",
    wholesale_price: "Wholesale Price",
    edit_product_btn: "Edit Product",
    view_quote: "View Quote",
    edit_quote_action: "Edit Quote",
    create_sales_invoice: "Create Sales Invoice",
    create_purchase_invoice: "Create Purchase Invoice",
    download_pdf_quote: "Download PDF",
    send_email_quote: "Send Quote via Email",
    delete_quote_action: "Delete Quote",
    quote_no: "Quote No",
    quote_no_title: "Quote Number",
    description: "Description",
    item_no: "No",
    data_entry: "Data Entry",
    updated_by: "Updated By",
    updated_at: "Updated At",
    sold_qty: "Sold Qty",
    total_no_vat: "Total (No VAT)",
    unit_price_no_vat: "Unit Price (No VAT)",
    unit_price_with_vat: "Unit Price (With VAT)",
    product_total: "Product Total",
    attach_documents: "Attach Documents",
    complete_process: "Complete Process",
    all_branches: "All Branches",
    shipping: "Shipping",
    view: "View",
    pdf_btn: "PDF",
    email_btn: "Email",
    edit_btn: "Edit",
    delete_btn: "Delete",
    edit: "Edit",
    select_customer: "Select Customer",
    delete_product: "Delete Product",
    showing_records: "Showing",
    to: "to",
    of: "of",
    records: "records",
    previous: "Previous",
    next: "Next",
    copy_suffix: "(Copy)",
    // Add Product
    add_product_title: "Add Product",
    add_product_desc: "Please enter the information below. Fields marked with * are mandatory.",
    product_type: "Product Type",
    general: "General",
    service: "Service",
    product_name: "Product Name",
    product_name_second_lang: "Product Name in Second Language",
    product_name_sec_lang: "Product Name in Second Language",
    product_name_third_lang: "Product Name in Third Language",
    product_code_required: "Product Code *",
    generate_code: "Generate Code",
    barcode_reader_hint: "Barcode reader can also be used",
    alt_code: "Alternative Code",
    select_brand: "Select Brand",
    product_cost: "Product Cost",
    product_price: "Product Price",
    max_order_qty: "Max Order Quantity",
    reorder_point: "Reorder Point",
    has_variants_label: "This product has multiple variants e.g. multiple sizes and/or colors",
    main_categories_required: "Main Categories *",
    select_main_categories: "Select Main Categories",
    sub_category: "Sub Category",
    select_category_load: "Please select category to load",
    product_unit: "Product Unit",
    select_unit: "Select Unit",
    default_sale_unit: "Default Sale Unit",
    default_purchase_unit: "Default Purchase Unit",
    additional_units: "Additional Units",
    list_price_branch_order_limit: "List Price & Order Limit for Branches",
    branch_name: "Branch Name",
    list_amount: "List Amount",
    stock_alerts_header: "Stock Alerts",
    accuracy_solutions_company: "Accuracy Solutions Company",
    product_availability_branches: "Product Availability in Branches",
    status_header: "Status",
    yes: "Yes",
    no: "No",
    product_image: "Product Image",
    browse: "Browse ...",
    product_gallery: "Product Gallery",
    stock_item: "Stock Item",
    hide_pos: "Hide in POS",
    featured_product: "Featured (Place in store home if enabled)",
    new_arrival: "New Arrival",
    hide_store: "Hide in Store",
    product_details: "Product Details",
    // Import Products
    import_products_csv: "Import Products via CSV",
    download_sample_file: "Download Sample File",
    csv_instruction_1: "The first line in the uploaded CSV file should remain as is. Please do not change the order of columns.",
    csv_instruction_2: "Correct column order...",
    csv_instruction_3: "Images must be uploaded to assets/uploads/ folder...",
    csv_instruction_4: "The system will check if the code belongs to any existing products. Otherwise, the product will be added as new.",
    upload_file: "Upload File",
    import: "Import",
    // Print Barcode
    print_barcode_labels_title: "Print Barcode - Labels",
    sales_all_branches: "Sales (All Branches)",
    sales_table_desc: "Data shown for the last 30 days. Please use the form to show more results",
    grand_total: "Grand Total",
    remaining_amount: "Remaining Amount",
    payment_type: "Payment Type",
    returned: "Returned",
    returned_status: "Returned",
    partial: "Partial",
    mada: "Mada",
    view_invoice: "View Invoice",
    edit_sale: "Edit Sale",
    return_sale: "Return Sale",
    delete_sale: "Delete Sale",
    total_records: "Total Records",
    invoice_details: "Invoice Details",
    duplicate_sale: "Duplicate Sale",
    view_payments: "View Payments",
    add_payment: "Add Payment",
    store_bond: "Store Bond",
    claim_bond: "Claim Bond",
    add_delivery: "Add Delivery",
    download_pdf: "Download PDF",
    download_excel: "Download Excel",
    download_csv: "Download CSV",
    send_email: "Send Invoice via Email",
    send_whatsapp: "Send Invoice via WhatsApp",
    release_bond: "Release Bond",
    edit_delegate: "Edit Delegate / Employee",
    gift_cards_list: "Gift Cards List",
    add_gift_card: "Add Gift Card",
    delete_gift_cards: "Delete Gift Cards",
    card_no: "Card No",
    value: "Value",
    notes: "Notes",
    expiry_date: "Expiry Date",
    walk_in_customer: "Walk-in Customer",
    use_employee_points_program: "Use Employee Points Program",
    gift_cards_table_desc: "Please use the table below to navigate or filter results.",
    no_data_in_table: "No data in table",
    payment_view_title: "View Payments (Sale Ref: {ref})",
    store_bond_title: "Store Bond",
    claim_letter_title: "Financial Claim Letter Template",
    delivery_title: "Add Delivery",
    delivery_status: "Status *",
    delivery_ref: "Delivery Reference",
    sale_ref: "Sale Reference *",
    address: "Address *",
    attachments: "Attachments",
    note: "Note",
    add_delivery_btn: "Add Delivery",
    edit_payment: "Edit Payment",
    edit_payment_desc: "Please enter the information below. Fields marked with * are mandatory.",
    payment_ref: "Reference No",
    receipt_bond: "Receipt Bond",
    received_from: "Received from",
    amount_of: "Amount of",
    for_payment: "For",
    seal_signature: "Seal or Signature",
    receiver: "Receiver",
    email_sent_success: "Email sent successfully",
    print_barcode_desc: "You can visit Main Categories, Sub Categories, Purchases and Stock Transfers to add products to the print list",
    add_product_label: "Add Product",
    activity_name: "Activity Name",
    expiry: "Expiry",
    production: "Production",
    product_name_code: "Product Name (Product Code)",
    no_products_added: "No products added",
    print_method: "Print Method",
    continuous_print: "Continuous Print (Barcode Printer)",
    a4_paper: "A4 Paper",
    width: "Width",
    mm: "mm",
    height: "Height",
    barcode_height: "Barcode Height",
    px: "px",
    barcode_orientation: "Barcode Orientation",
    vertical: "Vertical",
    horizontal: "Horizontal",
    check_promo_price: "Check Promo Price",
    print: "Print",
    tax_inclusive: "Tax Inclusive",
    font_formatting: "Font Formatting",
    format_product_name: "Format Product Name",
    format_activity_name: "Format Activity Name",
    format_dates: "Format Production & Expiry Dates",
    format_price: "Format Price",
    font_size: "Font Size",
    spacing: "Spacing",
    font_color: "Font Color",
    bg_color: "Background Color",
    update: "Update",
    light_mode: "Light Mode",
    dark_mode: "Dark Mode",
    red_theme: "Red Theme",
    blue_theme: "Blue Theme",
    yellow_theme: "Yellow Theme",
    high_contrast: "High Contrast",
    filter_results: "Filter Results",
    from_date: "From Date",
    to_date: "To Date",
    export_to_excel: "Export to Excel file",
    export_to_pdf: "Export to pdf file",
    delete_selected_items: "Delete Selected Items",
    edit_delivery: "Edit Delivery",
    delivery_ref_no: "Delivery Reference No",
    sale_ref_no: "Sale Reference No",
    delivered_by: "Delivered By",
    received_by: "Received By",
    shelf: "Shelf",
    in_progress: "In Progress",
    delivered: "Delivered",
    delivery_failed: "Delivery Failed",
    financial_claim_letter: "Financial Claim Letter",
    sender: "Sender",
    recipient: "Recipient",
    subject: "Subject",
    financial_claim_subject: "Financial claim for payment of a specific amount",
    municipality_license: "Municipality License",
    sales_invoice: "Sales Invoice",
    product_description: "Product Description",
    price: "Price",
    customer_details: "Customer Details",
    customer_no: "Customer No",
    customer_name: "Customer Name",
    customer_tax_no: "Customer Tax No",
    mobile_no: "Mobile No",
    city: "City",
    district: "District",
    street_name: "Street Name",
    tax_no: "Tax No",
    unit_price: "Unit Price",
    pay: "Pay",
    delivery: "Delivery",
    view_payments_ref: "View Payments (Sale Ref: {ref})",
    invoice_date: "Invoice Date",
    invoice_type: "Invoice Type",
    thank_you: "Thank you for your visit",
    see_you_again: "See you again",
    return_policy: "Return and exchange within 48 hours",
    bring_invoice: "Invoice must be brought",
    dear: "Dear",
    greetings: "Greetings",
    claim_letter_body_1: "We would like to remind you that invoice number {invoiceNo} issued on {date} related to the amount of {amount} SAR ({amountText}) was supposed to be paid by __________ and until the date of this letter, the invoice amount has not been received.",
    claim_letter_body_2: "Therefore, we request you to pay the due amount within 7 days from its date, through the bank account attached to the invoice.",
    claim_letter_body_3: "In case of non-payment within the specified period, we will unfortunately be forced to take the necessary legal measures to collect the dues.",
    best_regards: "Best regards.",
    company_stamp: "Company Stamp",
    sales_report_by_category: "Sales Report by Category",
    customize_report_below: "Please customize the report below",
    total_sales_report: "Total Sales",
    profit: "Profit",
    show_records: "Show",
    category_code_placeholder: "[Category Code]",
    category_name_placeholder: "[Category Name]",
    treasuries: "Treasuries",
    treasurys: "Treasuries",
    treasurys_list: "Treasuries List",
    treasuries_page_title: "Treasuries List",
    treasury_code: "Treasury Code",
    treasury_name: "Treasury Name",
    treasury_opening_balance: "Opening Balance",
    treasury_search_placeholder: "Search by code or name...",
    add_treasury_btn: "Add Treasury",
    deleted_successfully: "Deleted successfully",
    something_went_wrong: "Something went wrong",
    no_data: "No data",
   
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const { systemSettings } = useSettings();
  const [language, setLanguageState] = useState<Language>(() => {
    // Initial load from settings if available, otherwise localStorage
    const savedLang = localStorage.getItem("language");
    if (savedLang) return savedLang as Language;

    return systemSettings.site.language.toLowerCase().includes("en") ? "en" : "ar";
  });

  // Sync with system settings when they change
  useEffect(() => {
    const targetLang = systemSettings.site.language.toLowerCase().includes("en") ? "en" : "ar";
    if (language !== targetLang) {
      setLanguageState(targetLang);
    }
  }, [systemSettings.site.language]);

  const direction = language === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    const root = window.document.documentElement;
    root.setAttribute("lang", language);
    root.setAttribute("dir", direction);
    localStorage.setItem("language", language);
  }, [language, direction]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return <LanguageContext.Provider value={{ language, direction, dir: direction, setLanguage, t }}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
